///
/// Auto-generated by Stone, do not modify.
///

#import "DBXBase.h"

@implementation DBXBase 

- (instancetype)initWithTransportClient:(DBXTransportClient *)client {
    self = [super init];
    if (self) {
        _authRoutes = [[DBXAUTHRoutes alloc] init:client];
        _filesRoutes = [[DBXFILESRoutes alloc] init:client];
        _sharingRoutes = [[DBXSHARINGRoutes alloc] init:client];
        _usersRoutes = [[DBXUSERSRoutes alloc] init:client];
    }
    return self;
}
@end
