///
/// Auto-generated by Stone, do not modify.
///

#import "DbxErrors.h"
#import "DbxStoneBase.h"
#import "DbxTasks.h"
#import "DbxUsersAccount.h"
#import "DbxUsersAccountType.h"
#import "DbxUsersBasicAccount.h"
#import "DbxUsersFullAccount.h"
#import "DbxUsersFullTeam.h"
#import "DbxUsersGetAccountArg.h"
#import "DbxUsersGetAccountBatchArg.h"
#import "DbxUsersGetAccountBatchError.h"
#import "DbxUsersGetAccountError.h"
#import "DbxUsersName.h"
#import "DbxUsersRouteObjects.h"
#import "DbxUsersRoutes.h"
#import "DbxUsersSpaceAllocation.h"
#import "DbxUsersSpaceUsage.h"
#import "DropboxTransportClient.h"

@implementation DbxUsersRoutes 

- (instancetype)init:(DropboxTransportClient *)client {
    self = [super init];
    if (self != nil) {
        _client = client;
    }
    return self;
}
- (DbxRpcTask *)getAccount:(NSString * _Nonnull)accountId {
    DbxRoute *route = DbxUsersRouteObjects.dbxUsersGetAccount;
    DbxUsersGetAccountArg *arg = [[DbxUsersGetAccountArg alloc] initWithAccountId:(NSString * _Nonnull)accountId];
    return [self.client requestRpc:route arg:arg];
}

- (DbxRpcTask *)getAccountBatch:(NSArray<NSString *> * _Nonnull)accountIds {
    DbxRoute *route = DbxUsersRouteObjects.dbxUsersGetAccountBatch;
    DbxUsersGetAccountBatchArg *arg = [[DbxUsersGetAccountBatchArg alloc] initWithAccountIds:(NSArray<NSString *> * _Nonnull)accountIds];
    return [self.client requestRpc:route arg:arg];
}

- (DbxRpcTask *)getCurrentAccount {
    DbxRoute *route = DbxUsersRouteObjects.dbxUsersGetCurrentAccount;
    return [self.client requestRpc:route arg:nil];
}

- (DbxRpcTask *)getSpaceUsage {
    DbxRoute *route = DbxUsersRouteObjects.dbxUsersGetSpaceUsage;
    return [self.client requestRpc:route arg:nil];
}

@end
