///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXUSERSName;

/// 
/// The Name struct.
/// 
/// Representations for a person's name to assist with internationalization.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXUSERSName : NSObject <DBXSerializable> 

/// Also known as a first name.
@property (nonatomic, readonly, copy) NSString * _Nonnull givenName;

/// Also known as a last name or family name.
@property (nonatomic, readonly, copy) NSString * _Nonnull surname;

/// Locale-dependent name. In the US, a person's familiar name is their
/// givenName, but elsewhere, it could be any combination of a person's
/// givenName and surname.
@property (nonatomic, readonly, copy) NSString * _Nonnull familiarName;

/// A name that can be used directly to represent the name of a user's Dropbox
/// account.
@property (nonatomic, readonly, copy) NSString * _Nonnull displayName;

/// 
/// Full constructor for the `DBXUSERSName` struct (exposes all instance
/// variables).
/// 
/// - parameter givenName: Also known as a first name.
/// - parameter surname: Also known as a last name or family name.
/// - parameter familiarName: Locale-dependent name. In the US, a person's
/// familiar name is their :field:`given_name`, but elsewhere, it could be any
/// combination of a person's :field:`given_name` and :field:`surname`.
/// - parameter displayName: A name that can be used directly to represent the
/// name of a user's Dropbox account.
/// 
/// - returns: An initialized `DBXUSERSName` instance.
/// 
- (nonnull instancetype)initWithGivenName:(NSString * _Nonnull)givenName surname:(NSString * _Nonnull)surname familiarName:(NSString * _Nonnull)familiarName displayName:(NSString * _Nonnull)displayName;

@end


/// 
/// The serialization class for the Name struct.
/// 
@interface DBXUSERSNameSerializer : NSObject 

/// 
/// Serializes `DBXUSERSName` instances.
/// 
///  - parameter instance: An instance of the `DBXUSERSName` API object.
/// 
///  - returns: A json-compatible dictionary representation of the
/// `DBXUSERSName` API object.
/// 
+ (NSDictionary * _Nonnull)serialize:(DBXUSERSName * _Nonnull)instance;

/// 
/// Deserializes `DBXUSERSName` instances.
/// 
///  - parameter dict: A json-compatible dictionary representation of the
/// `DBXUSERSName` API object.
/// 
///  - returns: An instantiation of the `DBXUSERSName` object.
/// 
+ (DBXUSERSName * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
