///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DbxStoneSerializers.h"

@class DbxFilesFileMetadata;
@class DbxFilesUploadSessionFinishBatchResultEntry;
@class DbxFilesUploadSessionFinishError;

/// 
/// The DbxFilesUploadSessionFinishBatchResultEntry union.
/// 
@interface DbxFilesUploadSessionFinishBatchResultEntry : NSObject <DbxSerializable> 

typedef NS_ENUM(NSInteger, FilesUploadSessionFinishBatchResultEntryTag) {
    /// (no description)
    FilesUploadSessionFinishBatchResultEntrySuccess,
    /// (no description)
    FilesUploadSessionFinishBatchResultEntryFailure,
};

- (nonnull instancetype)initWithSuccess:(DbxFilesFileMetadata * _Nonnull)success;

- (nonnull instancetype)initWithFailure:(DbxFilesUploadSessionFinishError * _Nonnull)failure;

- (BOOL)isSuccess;

- (BOOL)isFailure;

- (NSString * _Nonnull)getTagName;

+ (NSDictionary * _Nonnull)serialize:(id _Nonnull)obj;

+ (id _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

- (NSString * _Nonnull)description;

/// Current state of the DbxFilesUploadSessionFinishBatchResultEntry union type.
@property (nonatomic) FilesUploadSessionFinishBatchResultEntryTag tag;
@property (nonatomic) DbxFilesFileMetadata * _Nonnull success;
@property (nonatomic) DbxFilesUploadSessionFinishError * _Nonnull failure;

@end


@interface DbxFilesUploadSessionFinishBatchResultEntrySerializer : NSObject 

+ (NSDictionary * _Nonnull)serialize:(DbxFilesUploadSessionFinishBatchResultEntry * _Nonnull)obj;

+ (DbxFilesUploadSessionFinishBatchResultEntry * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
