///
/// Auto-generated by Stone, do not modify.
///

#import "DbxFilesGetTemporaryLinkError.h"
#import "DbxFilesLookupError.h"
#import "DbxStoneSerializers.h"
#import "DbxStoneValidators.h"

@implementation DbxFilesGetTemporaryLinkError 

- (instancetype)initWithPath:(DbxFilesLookupError *)path {
    self = [super init];
    if (self != nil) {
        _tag = (FilesGetTemporaryLinkErrorTag)FilesGetTemporaryLinkErrorPath;
        _path = path;
    }
    return self;
}

- (instancetype)initWithOther {
    self = [super init];
    if (self != nil) {
        _tag = (FilesGetTemporaryLinkErrorTag)FilesGetTemporaryLinkErrorOther;
    }
    return self;
}

- (BOOL)isPath {
    return _tag == (FilesGetTemporaryLinkErrorTag)FilesGetTemporaryLinkErrorPath;
}

- (BOOL)isOther {
    return _tag == (FilesGetTemporaryLinkErrorTag)FilesGetTemporaryLinkErrorOther;
}

- (NSString *)getTagName {
    if (_tag == (FilesGetTemporaryLinkErrorTag)FilesGetTemporaryLinkErrorPath) {
        return @"(FilesGetTemporaryLinkErrorTag)FilesGetTemporaryLinkErrorPath";
    }
    if (_tag == (FilesGetTemporaryLinkErrorTag)FilesGetTemporaryLinkErrorOther) {
        return @"(FilesGetTemporaryLinkErrorTag)FilesGetTemporaryLinkErrorOther";
    }

    @throw([NSException exceptionWithName:@"InvalidTagEnum" reason:@"Supplied tag enum has an invalid value." userInfo:nil]);
}

- (DbxFilesLookupError *)path {
    if (_tag != (FilesGetTemporaryLinkErrorTag)FilesGetTemporaryLinkErrorPath) {
        [NSException raise:@"IllegalStateException" format:@"Invalid tag: required (FilesGetTemporaryLinkErrorTag)FilesGetTemporaryLinkErrorPath, but was %@.", [self getTagName]];
    }
    return _path;
}

+ (NSDictionary *)serialize:(id)obj {
    return [DbxFilesGetTemporaryLinkErrorSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DbxFilesGetTemporaryLinkErrorSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DbxFilesGetTemporaryLinkErrorSerializer serialize:self] description];
}

@end


@implementation DbxFilesGetTemporaryLinkErrorSerializer 

+ (NSDictionary *)serialize:(DbxFilesGetTemporaryLinkError *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    if ([valueObj isPath]) {
        jsonDict[@"path"] = [DbxFilesLookupErrorSerializer serialize:valueObj.path];
        jsonDict[@".tag"] = @"path";
    }
    else if ([valueObj isOther]) {
        jsonDict[@".tag"] = @"other";
    }
    else {
        @throw([NSException exceptionWithName:@"InvalidTagEnum" reason:@"Supplied tag enum has an invalid value." userInfo:nil]);
    }

    return jsonDict;
}

+ (DbxFilesGetTemporaryLinkError *)deserialize:(NSDictionary *)valueDict {
    NSString *tag = valueDict[@".tag"];

    if ([tag isEqualToString:@"path"]) {
        DbxFilesLookupError *path = [DbxFilesLookupErrorSerializer deserialize:valueDict[@"path"]];
        return [[DbxFilesGetTemporaryLinkError alloc] initWithPath:path];
    }
    if ([tag isEqualToString:@"other"]) {
        return [[DbxFilesGetTemporaryLinkError alloc] initWithOther];
    }

    @throw([NSException exceptionWithName:@"InvalidTagEnum" reason:@"Supplied tag enum has an invalid value." userInfo:nil]);
}

@end
