///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DbxStoneSerializers.h"

@class DbxFilesMediaInfo;
@class DbxFilesMediaMetadata;

/// 
/// The DbxFilesMediaInfo union.
/// 
@interface DbxFilesMediaInfo : NSObject <DbxSerializable> 

typedef NS_ENUM(NSInteger, FilesMediaInfoTag) {
    /// Indicate the photo/video is still under processing and metadata is not
    /// available yet.
    FilesMediaInfoPending,
    /// The metadata for the photo/video.
    FilesMediaInfoMetadata,
};

- (nonnull instancetype)initWithPending;

- (nonnull instancetype)initWithMetadata:(DbxFilesMediaMetadata * _Nonnull)metadata;

- (BOOL)isPending;

- (BOOL)isMetadata;

- (NSString * _Nonnull)getTagName;

- (NSString * _Nonnull)description;

/// Current state of the DbxFilesMediaInfo union type.
@property (nonatomic) FilesMediaInfoTag tag;
@property (nonatomic) DbxFilesMediaMetadata * _Nonnull metadata;

@end


@interface DbxFilesMediaInfoSerializer : NSObject 

+ (NSDictionary * _Nonnull)serialize:(DbxFilesMediaInfo * _Nonnull)obj;

+ (DbxFilesMediaInfo * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
