///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXFILESThumbnailSize;

/// 
/// The `DBXFILESThumbnailSize` union.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXFILESThumbnailSize : NSObject <DBXSerializable> 

/// The `DBXFILESThumbnailSizeTag` enum type represents the possible tag states
/// that the `DBXFILESThumbnailSize` union can exist in.
typedef NS_ENUM(NSInteger, DBXFILESThumbnailSizeTag) {
    /// 32 by 32 px.
    DBXFILESThumbnailSizeW32h32,

    /// 64 by 64 px.
    DBXFILESThumbnailSizeW64h64,

    /// 128 by 128 px.
    DBXFILESThumbnailSizeW128h128,

    /// 640 by 480 px.
    DBXFILESThumbnailSizeW640h480,

    /// 1024 by 768
    DBXFILESThumbnailSizeW1024h768,

};

/// Represents the union's current tag state.
@property (nonatomic) DBXFILESThumbnailSizeTag tag;

/// Initializes union class with tag state of `W32h32`.
- (nonnull instancetype)initWithW32h32;

/// Initializes union class with tag state of `W64h64`.
- (nonnull instancetype)initWithW64h64;

/// Initializes union class with tag state of `W128h128`.
- (nonnull instancetype)initWithW128h128;

/// Initializes union class with tag state of `W640h480`.
- (nonnull instancetype)initWithW640h480;

/// Initializes union class with tag state of `W1024h768`.
- (nonnull instancetype)initWithW1024h768;

/// Returns whether the union's current tag state has value `W32h32`.
- (BOOL)isW32h32;

/// Returns whether the union's current tag state has value `W64h64`.
- (BOOL)isW64h64;

/// Returns whether the union's current tag state has value `W128h128`.
- (BOOL)isW128h128;

/// Returns whether the union's current tag state has value `W640h480`.
- (BOOL)isW640h480;

/// Returns whether the union's current tag state has value `W1024h768`.
- (BOOL)isW1024h768;

/// Returns a human-readable string representing the union's current tag state.
- (NSString * _Nonnull)getTagName;

/// Returns a human-readable representation of the `DBXFILESThumbnailSize`
/// object.
- (NSString * _Nonnull)description;

@end


/// 
/// The serialization class for the `DBXFILESThumbnailSize` union.
/// 
@interface DBXFILESThumbnailSizeSerializer : NSObject 

/// Returns a json-compatible dictionary representation of the
/// `DBXFILESThumbnailSize` object from an instantiation.
+ (NSDictionary * _Nonnull)serialize:(DBXFILESThumbnailSize * _Nonnull)obj;

/// Returns an instantiation of the `DBXFILESThumbnailSize` object from a
/// json-compatible dictionary representation.
+ (DBXFILESThumbnailSize * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
