///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXFILESPropertyGroupUpdate;
@class DBXFILESUpdatePropertyGroupArg;

/// 
/// The UpdatePropertyGroupArg struct.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXFILESUpdatePropertyGroupArg : NSObject <DBXSerializable> 

/// A unique identifier for the file.
@property (nonatomic, readonly, copy) NSString * _Nonnull path;

/// Filled custom property templates associated with a file.
@property (nonatomic, readonly) NSArray<DBXFILESPropertyGroupUpdate *> * _Nonnull updatePropertyGroups;

/// 
/// Full constructor for the `DBXFILESUpdatePropertyGroupArg` struct (exposes
/// all instance variables).
/// 
/// - parameter path: A unique identifier for the file.
/// - parameter updatePropertyGroups: Filled custom property templates
/// associated with a file.
/// 
/// - returns: An initialized `DBXFILESUpdatePropertyGroupArg` instance.
/// 
- (nonnull instancetype)initWithPath:(NSString * _Nonnull)path updatePropertyGroups:(NSArray<DBXFILESPropertyGroupUpdate *> * _Nonnull)updatePropertyGroups;

@end


/// 
/// The serialization class for the UpdatePropertyGroupArg struct.
/// 
@interface DBXFILESUpdatePropertyGroupArgSerializer : NSObject 

/// 
/// Serializes `DBXFILESUpdatePropertyGroupArg` instances.
/// 
///  - parameter instance: An instance of the `DBXFILESUpdatePropertyGroupArg`
/// API object.
/// 
///  - returns: A json-compatible dictionary representation of the
/// `DBXFILESUpdatePropertyGroupArg` API object.
/// 
+ (NSDictionary * _Nonnull)serialize:(DBXFILESUpdatePropertyGroupArg * _Nonnull)instance;

/// 
/// Deserializes `DBXFILESUpdatePropertyGroupArg` instances.
/// 
///  - parameter dict: A json-compatible dictionary representation of the
/// `DBXFILESUpdatePropertyGroupArg` API object.
/// 
///  - returns: An instantiation of the `DBXFILESUpdatePropertyGroupArg` object.
/// 
+ (DBXFILESUpdatePropertyGroupArg * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
