///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DbxStoneSerializers.h"
#import "DbxFilesInvalidPropertyGroupError.h"

@class DbxFilesLookUpPropertiesError;
@class DbxFilesLookupError;
@class DbxFilesUpdatePropertiesError;

/// 
/// The DbxFilesUpdatePropertiesError union.
/// 
@interface DbxFilesUpdatePropertiesError : NSObject <DbxSerializable> 

typedef NS_ENUM(NSInteger, FilesUpdatePropertiesErrorTag) {
    /// Property template does not exist for given identifier.
    FilesUpdatePropertiesErrorTemplateNotFound,
    /// You do not have the permissions to modify this property template.
    FilesUpdatePropertiesErrorRestrictedContent,
    /// (no description)
    FilesUpdatePropertiesErrorOther,
    /// (no description)
    FilesUpdatePropertiesErrorPath,
    /// A field value in this property group is too large.
    FilesUpdatePropertiesErrorPropertyFieldTooLarge,
    /// The property group specified does not conform to the property template.
    FilesUpdatePropertiesErrorDoesNotFitTemplate,
    /// (no description)
    FilesUpdatePropertiesErrorPropertyGroupLookup,
};

- (nonnull instancetype)initWithTemplateNotFound:(NSString * _Nonnull)templateNotFound;

- (nonnull instancetype)initWithRestrictedContent;

- (nonnull instancetype)initWithOther;

- (nonnull instancetype)initWithPath:(DbxFilesLookupError * _Nonnull)path;

- (nonnull instancetype)initWithPropertyFieldTooLarge;

- (nonnull instancetype)initWithDoesNotFitTemplate;

- (nonnull instancetype)initWithPropertyGroupLookup:(DbxFilesLookUpPropertiesError * _Nonnull)propertyGroupLookup;

- (BOOL)isTemplateNotFound;

- (BOOL)isRestrictedContent;

- (BOOL)isOther;

- (BOOL)isPath;

- (BOOL)isPropertyFieldTooLarge;

- (BOOL)isDoesNotFitTemplate;

- (BOOL)isPropertyGroupLookup;

- (NSString * _Nonnull)getTagName;

+ (NSDictionary * _Nonnull)serialize:(id _Nonnull)obj;

+ (id _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

- (NSString * _Nonnull)description;

/// Current state of the DbxFilesUpdatePropertiesError union type.
@property (nonatomic) FilesUpdatePropertiesErrorTag tag;
@property (nonatomic, copy) NSString * _Nonnull templateNotFound;
@property (nonatomic) DbxFilesLookupError * _Nonnull path;
@property (nonatomic) DbxFilesLookUpPropertiesError * _Nonnull propertyGroupLookup;

@end


@interface DbxFilesUpdatePropertiesErrorSerializer : NSObject 

+ (NSDictionary * _Nonnull)serialize:(DbxFilesUpdatePropertiesError * _Nonnull)obj;

+ (DbxFilesUpdatePropertiesError * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
