///
/// Auto-generated by Stone, do not modify.
///

#import "DBXFILESCreateFolderError.h"
#import "DBXFILESWriteError.h"
#import "DBXStoneSerializers.h"
#import "DBXStoneValidators.h"

@implementation DBXFILESCreateFolderError 

- (instancetype)initWithPath:(DBXFILESWriteError *)path {
    self = [super init];
    if (self != nil) {
        _tag = DBXFILESCreateFolderErrorPath;
        _path = path;
    }
    return self;
}

- (BOOL)isPath {
    return _tag == DBXFILESCreateFolderErrorPath;
}

- (NSString *)getTagName {
    switch (_tag) {
        case DBXFILESCreateFolderErrorPath:
           return @"DBXFILESCreateFolderErrorPath";
    }

    @throw([NSException exceptionWithName:@"InvalidTag" reason:@"Tag has an invalid value." userInfo:nil]);
}

- (DBXFILESWriteError *)path {
    if (_tag != DBXFILESCreateFolderErrorPath) {
        [NSException raise:@"IllegalStateException" format:@"Invalid tag: required `DBXFILESCreateFolderErrorPath`, but was %@.", [self getTagName]];
    }
    return _path;
}

+ (NSDictionary *)serialize:(id)obj {
    return [DBXFILESCreateFolderErrorSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DBXFILESCreateFolderErrorSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DBXFILESCreateFolderErrorSerializer serialize:self] description];
}

@end


@implementation DBXFILESCreateFolderErrorSerializer 

+ (NSDictionary *)serialize:(DBXFILESCreateFolderError *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    if ([valueObj isPath]) {
        jsonDict = [[DBXFILESWriteErrorSerializer serialize:valueObj.path] mutableCopy];
        jsonDict[@".tag"] = @"path";
    }
    else {
        @throw([NSException exceptionWithName:@"InvalidTag" reason:@"Tag has an invalid value." userInfo:nil]);
    }

    return jsonDict;
}

+ (DBXFILESCreateFolderError *)deserialize:(NSDictionary *)valueDict {
    NSString *tag = valueDict[@".tag"];

    if ([tag isEqualToString:@"path"]) {
        DBXFILESWriteError *path = [DBXFILESWriteErrorSerializer deserialize:valueDict[@"path"]];
        return [[DBXFILESCreateFolderError alloc] initWithPath:path];
    }

    @throw([NSException exceptionWithName:@"InvalidTag" reason:@"Tag has an invalid value." userInfo:nil]);
}

@end
