///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXFILESListRevisionsArg;

/// 
/// The ListRevisionsArg struct.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXFILESListRevisionsArg : NSObject <DBXSerializable> 

/// The path to the file you want to see the revisions of.
@property (nonatomic, readonly, copy) NSString * _Nonnull path;

/// The maximum number of revision entries returned.
@property (nonatomic, readonly, copy) NSNumber * _Nonnull limit;

/// 
/// Full constructor for the `DBXFILESListRevisionsArg` struct (exposes all
/// instance variables).
/// 
/// - parameter path: The path to the file you want to see the revisions of.
/// - parameter limit: The maximum number of revision entries returned.
/// 
/// - returns: An initialized `DBXFILESListRevisionsArg` instance.
/// 
- (nonnull instancetype)initWithPath:(NSString * _Nonnull)path limit:(NSNumber * _Nullable)limit;

/// 
/// Convenience constructor for the `DBXFILESListRevisionsArg` struct (exposes
/// only non-nullable instance variables with no default value).
/// 
/// - parameter path: The path to the file you want to see the revisions of.
/// 
/// - returns: An initialized `DBXFILESListRevisionsArg` instance.
/// 
- (nonnull instancetype)initWithPath:(NSString * _Nonnull)path;

@end


/// 
/// The serialization class for the ListRevisionsArg struct.
/// 
@interface DBXFILESListRevisionsArgSerializer : NSObject 

/// 
/// Serializes `DBXFILESListRevisionsArg` instances.
/// 
///  - parameter instance: An instance of the `DBXFILESListRevisionsArg` API
/// object.
/// 
///  - returns: A json-compatible dictionary representation of the
/// `DBXFILESListRevisionsArg` API object.
/// 
+ (NSDictionary * _Nonnull)serialize:(DBXFILESListRevisionsArg * _Nonnull)instance;

/// 
/// Deserializes `DBXFILESListRevisionsArg` instances.
/// 
///  - parameter dict: A json-compatible dictionary representation of the
/// `DBXFILESListRevisionsArg` API object.
/// 
///  - returns: An instantiation of the `DBXFILESListRevisionsArg` object.
/// 
+ (DBXFILESListRevisionsArg * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
