///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXFILESUploadSessionAppendArg;
@class DBXFILESUploadSessionCursor;

/// 
/// The `DBXFILESUploadSessionAppendArg` struct.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXFILESUploadSessionAppendArg : NSObject <DBXSerializable> 

/// Contains the upload session ID and the offset.
@property (nonatomic) DBXFILESUploadSessionCursor * _Nonnull cursor;

/// If true, the current session will be closed, at which point you won't be
/// able to call uploadSessionAppendV2 anymore with the current session.
@property (nonatomic, copy) NSNumber * _Nonnull close;

/// Full constructor for the `UploadSessionAppendArg` struct (exposes all
/// instance variables).
- (nonnull instancetype)initWithCursor:(DBXFILESUploadSessionCursor * _Nonnull)cursor close:(NSNumber * _Nullable)close;

/// Convenience constructor for the `UploadSessionAppendArg` struct (exposes
/// only non-nullable instance variables with no default value).
- (nonnull instancetype)initWithCursor:(DBXFILESUploadSessionCursor * _Nonnull)cursor;

/// Returns a human-readable representation of the
/// `DBXFILESUploadSessionAppendArg` object.
- (NSString * _Nonnull)description;

@end


/// 
/// The serialization class for the `DBXFILESUploadSessionAppendArg` struct.
/// 
@interface DBXFILESUploadSessionAppendArgSerializer : NSObject 

/// Returns a json-compatible dictionary representation of the
/// `DBXFILESUploadSessionAppendArg` object from an instantiation.
+ (NSDictionary * _Nonnull)serialize:(DBXFILESUploadSessionAppendArg * _Nonnull)obj;

/// Returns an instantiation of the `DBXFILESUploadSessionAppendArg` object from
/// a json-compatible dictionary representation.
+ (DBXFILESUploadSessionAppendArg * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
