///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXFILESListRevisionsArg;

/// 
/// The `DBXFILESListRevisionsArg` struct.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXFILESListRevisionsArg : NSObject <DBXSerializable> 

/// The path to the file you want to see the revisions of.
@property (nonatomic, copy) NSString * _Nonnull path;

/// The maximum number of revision entries returned.
@property (nonatomic, copy) NSNumber * _Nonnull limit;

/// Full constructor for the `ListRevisionsArg` struct (exposes all instance
/// variables).
- (nonnull instancetype)initWithPath:(NSString * _Nonnull)path limit:(NSNumber * _Nullable)limit;

/// Convenience constructor for the `ListRevisionsArg` struct (exposes only
/// non-nullable instance variables with no default value).
- (nonnull instancetype)initWithPath:(NSString * _Nonnull)path;

/// Returns a human-readable representation of the `DBXFILESListRevisionsArg`
/// object.
- (NSString * _Nonnull)description;

@end


/// 
/// The serialization class for the `DBXFILESListRevisionsArg` struct.
/// 
@interface DBXFILESListRevisionsArgSerializer : NSObject 

/// Returns a json-compatible dictionary representation of the
/// `DBXFILESListRevisionsArg` object from an instantiation.
+ (NSDictionary * _Nonnull)serialize:(DBXFILESListRevisionsArg * _Nonnull)obj;

/// Returns an instantiation of the `DBXFILESListRevisionsArg` object from a
/// json-compatible dictionary representation.
+ (DBXFILESListRevisionsArg * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
