///
/// Auto-generated by Stone, do not modify.
///

#import "DbxFilesFolderMetadata.h"
#import "DbxFilesFolderSharingInfo.h"
#import "DbxFilesMetadata.h"
#import "DbxPropertiesPropertyGroup.h"
#import "DbxStoneSerializers.h"
#import "DbxStoneValidators.h"

@implementation DbxFilesFolderMetadata 

- (instancetype)initWithName:(NSString *)name id_:(NSString *)id_ pathLower:(NSString *)pathLower pathDisplay:(NSString *)pathDisplay parentSharedFolderId:(NSString *)parentSharedFolderId sharedFolderId:(NSString *)sharedFolderId sharingInfo:(DbxFilesFolderSharingInfo *)sharingInfo propertyGroups:(NSArray<DbxPropertiesPropertyGroup *> *)propertyGroups {
    [DbxStoneValidators stringValidator:[NSNumber numberWithInt:1] maxLength:nil pattern:nil](id_);
    [DbxStoneValidators nullableValidator:[DbxStoneValidators stringValidator:nil maxLength:nil pattern:@"[-_0-9a-zA-Z:]+"]](parentSharedFolderId);
    [DbxStoneValidators nullableValidator:[DbxStoneValidators stringValidator:nil maxLength:nil pattern:@"[-_0-9a-zA-Z:]+"]](sharedFolderId);
    [DbxStoneValidators nullableValidator:[DbxStoneValidators arrayValidator:nil maxItems:nil itemValidator:nil]](propertyGroups);

    self = [super initWithName:name pathLower:pathLower pathDisplay:pathDisplay parentSharedFolderId:parentSharedFolderId];
    if (self != nil) {
        _id_ = id_;
        _sharedFolderId = sharedFolderId;
        _sharingInfo = sharingInfo;
        _propertyGroups = propertyGroups;
    }
    return self;
}

- (instancetype)initWithName:(NSString *)name id_:(NSString *)id_ {
    return [self initWithName:name id_:id_ pathLower:nil pathDisplay:nil parentSharedFolderId:nil sharedFolderId:nil sharingInfo:nil propertyGroups:nil];
}

+ (NSDictionary *)serialize:(id)obj {
    return [DbxFilesFolderMetadataSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DbxFilesFolderMetadataSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DbxFilesFolderMetadataSerializer serialize:self] description];
}

@end


@implementation DbxFilesFolderMetadataSerializer 

+ (NSDictionary *)serialize:(DbxFilesFolderMetadata *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    jsonDict[@"name"] = [DbxStringSerializer serialize:valueObj.name];
    jsonDict[@"id"] = [DbxStringSerializer serialize:valueObj.id_];
    if (valueObj.pathLower != nil) {
        jsonDict[@"path_lower"] = [DbxStringSerializer serialize:valueObj.pathLower];
    }
    if (valueObj.pathDisplay != nil) {
        jsonDict[@"path_display"] = [DbxStringSerializer serialize:valueObj.pathDisplay];
    }
    if (valueObj.parentSharedFolderId != nil) {
        jsonDict[@"parent_shared_folder_id"] = [DbxStringSerializer serialize:valueObj.parentSharedFolderId];
    }
    if (valueObj.sharedFolderId != nil) {
        jsonDict[@"shared_folder_id"] = [DbxStringSerializer serialize:valueObj.sharedFolderId];
    }
    if (valueObj.sharingInfo != nil) {
        jsonDict[@"sharing_info"] = [DbxFilesFolderSharingInfoSerializer serialize:valueObj.sharingInfo];
    }
    if (valueObj.propertyGroups != nil) {
        jsonDict[@"property_groups"] = [DbxArraySerializer serialize:valueObj.propertyGroups withBlock:^id(id obj) { return [DbxPropertiesPropertyGroupSerializer serialize:obj]; }];
    }

    return jsonDict;
}

+ (DbxFilesFolderMetadata *)deserialize:(NSDictionary *)valueDict {
    NSString *name = [DbxStringSerializer deserialize:valueDict];
    NSString *id_ = [DbxStringSerializer deserialize:valueDict];
    NSString *pathLower = valueDict != nil ? [DbxStringSerializer deserialize:valueDict] : nil;
    NSString *pathDisplay = valueDict != nil ? [DbxStringSerializer deserialize:valueDict] : nil;
    NSString *parentSharedFolderId = valueDict != nil ? [DbxStringSerializer deserialize:valueDict] : nil;
    NSString *sharedFolderId = valueDict != nil ? [DbxStringSerializer deserialize:valueDict] : nil;
    DbxFilesFolderSharingInfo *sharingInfo = valueDict != nil ? [DbxFilesFolderSharingInfoSerializer deserialize:valueDict] : nil;
    NSArray<DbxPropertiesPropertyGroup *> *propertyGroups = valueDict != nil ? [DbxArraySerializer deserialize:valueDict withBlock:^id(id obj) { return [DbxPropertiesPropertyGroupSerializer deserialize:obj]; }] : nil;

    return [[DbxFilesFolderMetadata alloc] initWithName:name id_:id_ pathLower:pathLower pathDisplay:pathDisplay parentSharedFolderId:parentSharedFolderId sharedFolderId:sharedFolderId sharingInfo:sharingInfo propertyGroups:propertyGroups];
}

@end
