///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"
#import "DBXFILESSharingInfo.h"

@class DBXFILESFolderSharingInfo;

/// 
/// The FolderSharingInfo struct.
/// 
/// Sharing info for a folder which is contained in a shared folder or is a
/// shared folder mount point.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXFILESFolderSharingInfo : DBXFILESSharingInfo <DBXSerializable> 

/// Set if the folder is contained by a shared folder.
@property (nonatomic, readonly, copy) NSString * _Nullable parentSharedFolderId;

/// If this folder is a shared folder mount point, the ID of the shared folder
/// mounted at this location.
@property (nonatomic, readonly, copy) NSString * _Nullable sharedFolderId;

/// 
/// Full constructor for the `DBXFILESFolderSharingInfo` struct (exposes all
/// instance variables).
/// 
/// - parameter readOnly: True if the file or folder is inside a read-only
/// shared folder.
/// - parameter parentSharedFolderId: Set if the folder is contained by a shared
/// folder.
/// - parameter sharedFolderId: If this folder is a shared folder mount point,
/// the ID of the shared folder mounted at this location.
/// 
/// - returns: An initialized `DBXFILESFolderSharingInfo` instance.
/// 
- (nonnull instancetype)initWithReadOnly:(NSNumber * _Nonnull)readOnly parentSharedFolderId:(NSString * _Nullable)parentSharedFolderId sharedFolderId:(NSString * _Nullable)sharedFolderId;

/// 
/// Convenience constructor for the `DBXFILESFolderSharingInfo` struct (exposes
/// only non-nullable instance variables with no default value).
/// 
/// - parameter readOnly: True if the file or folder is inside a read-only
/// shared folder.
/// 
/// - returns: An initialized `DBXFILESFolderSharingInfo` instance.
/// 
- (nonnull instancetype)initWithReadOnly:(NSNumber * _Nonnull)readOnly;

@end


/// 
/// The serialization class for the FolderSharingInfo struct.
/// 
@interface DBXFILESFolderSharingInfoSerializer : NSObject 

/// 
/// Serializes `DBXFILESFolderSharingInfo` instances.
/// 
///  - parameter instance: An instance of the `DBXFILESFolderSharingInfo` API
/// object.
/// 
///  - returns: A json-compatible dictionary representation of the
/// `DBXFILESFolderSharingInfo` API object.
/// 
+ (NSDictionary * _Nonnull)serialize:(DBXFILESFolderSharingInfo * _Nonnull)instance;

/// 
/// Deserializes `DBXFILESFolderSharingInfo` instances.
/// 
///  - parameter dict: A json-compatible dictionary representation of the
/// `DBXFILESFolderSharingInfo` API object.
/// 
///  - returns: An instantiation of the `DBXFILESFolderSharingInfo` object.
/// 
+ (DBXFILESFolderSharingInfo * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
