///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXFILESGetCopyReferenceError;
@class DBXFILESLookupError;

/// 
/// The `DBXFILESGetCopyReferenceError` union.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXFILESGetCopyReferenceError : NSObject <DBXSerializable> 

/// The `DBXFILESGetCopyReferenceErrorTag` enum type represents the possible tag
/// states that the `DBXFILESGetCopyReferenceError` union can exist in.
typedef NS_ENUM(NSInteger, DBXFILESGetCopyReferenceErrorTag) {
    /// (no description).
    DBXFILESGetCopyReferenceErrorPath,

    /// (no description).
    DBXFILESGetCopyReferenceErrorOther,

};

/// Represents the union's current tag state.
@property (nonatomic) DBXFILESGetCopyReferenceErrorTag tag;

/// (no description).
@property (nonatomic) DBXFILESLookupError * _Nonnull path;

/// Initializes union class with tag state of `Path`.
- (nonnull instancetype)initWithPath:(DBXFILESLookupError * _Nonnull)path;

/// Initializes union class with tag state of `Other`.
- (nonnull instancetype)initWithOther;

/// Returns whether the union's current tag state has value `Path`.
- (BOOL)isPath;

/// Returns whether the union's current tag state has value `Other`.
- (BOOL)isOther;

/// Returns a human-readable string representing the union's current tag state.
- (NSString * _Nonnull)getTagName;

/// Returns a human-readable representation of the
/// `DBXFILESGetCopyReferenceError` object.
- (NSString * _Nonnull)description;

@end


/// 
/// The serialization class for the `DBXFILESGetCopyReferenceError` union.
/// 
@interface DBXFILESGetCopyReferenceErrorSerializer : NSObject 

/// Returns a json-compatible dictionary representation of the
/// `DBXFILESGetCopyReferenceError` object from an instantiation.
+ (NSDictionary * _Nonnull)serialize:(DBXFILESGetCopyReferenceError * _Nonnull)obj;

/// Returns an instantiation of the `DBXFILESGetCopyReferenceError` object from
/// a json-compatible dictionary representation.
+ (DBXFILESGetCopyReferenceError * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
