///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXFILESFileMetadata;
@class DBXFILESSaveUrlResult;

/// 
/// The `DBXFILESSaveUrlResult` union.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXFILESSaveUrlResult : NSObject <DBXSerializable> 

/// The `DBXFILESSaveUrlResultTag` enum type represents the possible tag states
/// that the `DBXFILESSaveUrlResult` union can exist in.
typedef NS_ENUM(NSInteger, DBXFILESSaveUrlResultTag) {
    /// This response indicates that the processing is asynchronous. The string
    /// is an id that can be used to obtain the status of the asynchronous job.
    DBXFILESSaveUrlResultAsyncJobId,

    /// Metadata of the file where the URL is saved to.
    DBXFILESSaveUrlResultComplete,

};

/// Represents the union's current tag state.
@property (nonatomic) DBXFILESSaveUrlResultTag tag;

/// This response indicates that the processing is asynchronous. The string is
/// an id that can be used to obtain the status of the asynchronous job.
@property (nonatomic, copy) NSString * _Nonnull asyncJobId;

/// Metadata of the file where the URL is saved to.
@property (nonatomic) DBXFILESFileMetadata * _Nonnull complete;

/// Initializes union class with tag state of `AsyncJobId`.
- (nonnull instancetype)initWithAsyncJobId:(NSString * _Nonnull)asyncJobId;

/// Initializes union class with tag state of `Complete`.
- (nonnull instancetype)initWithComplete:(DBXFILESFileMetadata * _Nonnull)complete;

/// Returns whether the union's current tag state has value `AsyncJobId`.
- (BOOL)isAsyncJobId;

/// Returns whether the union's current tag state has value `Complete`.
- (BOOL)isComplete;

/// Returns a human-readable string representing the union's current tag state.
- (NSString * _Nonnull)getTagName;

/// Returns a human-readable representation of the `DBXFILESSaveUrlResult`
/// object.
- (NSString * _Nonnull)description;

@end


/// 
/// The serialization class for the `DBXFILESSaveUrlResult` union.
/// 
@interface DBXFILESSaveUrlResultSerializer : NSObject 

/// Returns a json-compatible dictionary representation of the
/// `DBXFILESSaveUrlResult` object from an instantiation.
+ (NSDictionary * _Nonnull)serialize:(DBXFILESSaveUrlResult * _Nonnull)obj;

/// Returns an instantiation of the `DBXFILESSaveUrlResult` object from a
/// json-compatible dictionary representation.
+ (DBXFILESSaveUrlResult * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
