///
/// Auto-generated by Stone, do not modify.
///

#import "DbxFilesMediaInfo.h"
#import "DbxFilesMediaMetadata.h"
#import "DbxStoneSerializers.h"
#import "DbxStoneValidators.h"

@implementation DbxFilesMediaInfo 

- (instancetype)initWithPending {
    self = [super init];
    if (self != nil) {
        _tag = (FilesMediaInfoTag)FilesMediaInfoPending;
    }
    return self;
}

- (instancetype)initWithMetadata:(DbxFilesMediaMetadata *)metadata {
    self = [super init];
    if (self != nil) {
        _tag = (FilesMediaInfoTag)FilesMediaInfoMetadata;
        _metadata = metadata;
    }
    return self;
}

- (BOOL)isPending {
    return _tag == (FilesMediaInfoTag)FilesMediaInfoPending;
}

- (BOOL)isMetadata {
    return _tag == (FilesMediaInfoTag)FilesMediaInfoMetadata;
}

- (NSString *)getTagName {
    if (_tag == (FilesMediaInfoTag)FilesMediaInfoPending) {
        return @"(FilesMediaInfoTag)FilesMediaInfoPending";
    }
    if (_tag == (FilesMediaInfoTag)FilesMediaInfoMetadata) {
        return @"(FilesMediaInfoTag)FilesMediaInfoMetadata";
    }

    @throw([NSException exceptionWithName:@"InvalidTagEnum" reason:@"Supplied tag enum has an invalid value." userInfo:nil]);
}

- (DbxFilesMediaMetadata *)metadata {
    if (_tag != (FilesMediaInfoTag)FilesMediaInfoMetadata) {
        [NSException raise:@"IllegalStateException" format:@"Invalid tag: required (FilesMediaInfoTag)FilesMediaInfoMetadata, but was %@.", [self getTagName]];
    }
    return _metadata;
}

+ (NSDictionary *)serialize:(id)obj {
    return [DbxFilesMediaInfoSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DbxFilesMediaInfoSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DbxFilesMediaInfoSerializer serialize:self] description];
}

@end


@implementation DbxFilesMediaInfoSerializer 

+ (NSDictionary *)serialize:(DbxFilesMediaInfo *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    if ([valueObj isPending]) {
        jsonDict[@".tag"] = @"pending";
    }
    else if ([valueObj isMetadata]) {
        jsonDict[@"metadata"] = [DbxFilesMediaMetadataSerializer serialize:valueObj.metadata];
        jsonDict[@".tag"] = @"metadata";
    }
    else {
        @throw([NSException exceptionWithName:@"InvalidTagEnum" reason:@"Supplied tag enum has an invalid value." userInfo:nil]);
    }

    return jsonDict;
}

+ (DbxFilesMediaInfo *)deserialize:(NSDictionary *)valueDict {
    NSString *tag = valueDict[@".tag"];

    if ([tag isEqualToString:@"pending"]) {
        return [[DbxFilesMediaInfo alloc] initWithPending];
    }
    if ([tag isEqualToString:@"metadata"]) {
        DbxFilesMediaMetadata *metadata = [DbxFilesMediaMetadataSerializer deserialize:valueDict[@"metadata"]];
        return [[DbxFilesMediaInfo alloc] initWithMetadata:metadata];
    }

    @throw([NSException exceptionWithName:@"InvalidTagEnum" reason:@"Supplied tag enum has an invalid value." userInfo:nil]);
}

@end
