///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DbxSerializable.h"

@class DbxFilesUploadSessionFinishBatchResult;
@class DbxFilesUploadSessionFinishBatchResultEntry;

/// 
/// The `DbxFilesUploadSessionFinishBatchResult` struct.
/// 
/// This class implements the `DbxSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DbxFilesUploadSessionFinishBatchResult : NSObject <DbxSerializable> 

/// Commit result for each file in the batch.
@property (nonatomic) NSArray<DbxFilesUploadSessionFinishBatchResultEntry *> * _Nonnull entries;

/// Full constructor for the `UploadSessionFinishBatchResult` struct (exposes
/// all instance variables).
- (nonnull instancetype)initWithEntries:(NSArray<DbxFilesUploadSessionFinishBatchResultEntry *> * _Nonnull)entries;

/// Returns a human-readable representation of the
/// `DbxFilesUploadSessionFinishBatchResult` object.
- (NSString * _Nonnull)description;

@end


/// 
/// The serialization class for the `DbxFilesUploadSessionFinishBatchResult`
/// struct.
/// 
@interface DbxFilesUploadSessionFinishBatchResultSerializer : NSObject 

/// Returns a json-compatible dictionary representation of the
/// `DbxFilesUploadSessionFinishBatchResult` object from an instantiation.
+ (NSDictionary * _Nonnull)serialize:(DbxFilesUploadSessionFinishBatchResult * _Nonnull)obj;

/// Returns an instantiation of the `DbxFilesUploadSessionFinishBatchResult`
/// object from a json-compatible dictionary representation.
+ (DbxFilesUploadSessionFinishBatchResult * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
