///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXFILESRelocationArg;

/// 
/// The `DBXFILESRelocationArg` struct.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXFILESRelocationArg : NSObject <DBXSerializable> 

/// Path in the user's Dropbox to be copied or moved.
@property (nonatomic, readonly, copy) NSString * _Nonnull fromPath;

/// Path in the user's Dropbox that is the destination.
@property (nonatomic, readonly, copy) NSString * _Nonnull toPath;

/// Full constructor for the `RelocationArg` struct (exposes all instance
/// variables).
- (nonnull instancetype)initWithFromPath:(NSString * _Nonnull)fromPath toPath:(NSString * _Nonnull)toPath;

@end


/// 
/// The serialization class for the `DBXFILESRelocationArg` struct.
/// 
@interface DBXFILESRelocationArgSerializer : NSObject 

/// Returns a json-compatible dictionary representation of the
/// `DBXFILESRelocationArg` object from an instantiation.
+ (NSDictionary * _Nonnull)serialize:(DBXFILESRelocationArg * _Nonnull)obj;

/// Returns an instantiation of the `DBXFILESRelocationArg` object from a
/// json-compatible dictionary representation.
+ (DBXFILESRelocationArg * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
