///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXFILESRemovePropertiesArg;

/// 
/// The RemovePropertiesArg struct.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXFILESRemovePropertiesArg : NSObject <DBXSerializable> 

/// A unique identifier for the file.
@property (nonatomic, readonly, copy) NSString * _Nonnull path;

/// A list of identifiers for a property template created by route
/// properties/template/add.
@property (nonatomic, readonly) NSArray<NSString *> * _Nonnull propertyTemplateIds;

/// 
/// Full constructor for the `DBXFILESRemovePropertiesArg` struct (exposes all
/// instance variables).
/// 
/// - parameter path: A unique identifier for the file.
/// - parameter propertyTemplateIds: A list of identifiers for a property
/// template created by route properties/template/add.
/// 
/// - returns: An initialized `DBXFILESRemovePropertiesArg` instance.
/// 
- (nonnull instancetype)initWithPath:(NSString * _Nonnull)path propertyTemplateIds:(NSArray<NSString *> * _Nonnull)propertyTemplateIds;

@end


/// 
/// The serialization class for the RemovePropertiesArg struct.
/// 
@interface DBXFILESRemovePropertiesArgSerializer : NSObject 

/// 
/// Serializes `DBXFILESRemovePropertiesArg` instances.
/// 
///  - parameter instance: An instance of the `DBXFILESRemovePropertiesArg` API
/// object.
/// 
///  - returns: A json-compatible dictionary representation of the
/// `DBXFILESRemovePropertiesArg` API object.
/// 
+ (NSDictionary * _Nonnull)serialize:(DBXFILESRemovePropertiesArg * _Nonnull)instance;

/// 
/// Deserializes `DBXFILESRemovePropertiesArg` instances.
/// 
///  - parameter dict: A json-compatible dictionary representation of the
/// `DBXFILESRemovePropertiesArg` API object.
/// 
///  - returns: An instantiation of the `DBXFILESRemovePropertiesArg` object.
/// 
+ (DBXFILESRemovePropertiesArg * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
