///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXFILESDownloadError;
@class DBXFILESLookupError;

/// 
/// The `DBXFILESDownloadError` union.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXFILESDownloadError : NSObject <DBXSerializable> 

/// The `DBXFILESDownloadErrorTag` enum type represents the possible tag states
/// that the `DBXFILESDownloadError` union can exist in.
typedef NS_ENUM(NSInteger, DBXFILESDownloadErrorTag) {
    /// (no description).
    DBXFILESDownloadErrorPath,

    /// (no description).
    DBXFILESDownloadErrorOther,

};

/// Represents the union's current tag state.
@property (nonatomic, readonly) DBXFILESDownloadErrorTag tag;

/// (no description).
@property (nonatomic, readonly) DBXFILESLookupError * _Nonnull path;

/// Initializes union class with tag state of `Path`.
- (nonnull instancetype)initWithPath:(DBXFILESLookupError * _Nonnull)path;

/// Initializes union class with tag state of `Other`.
- (nonnull instancetype)initWithOther;

/// Returns whether the union's current tag state has value `Path`.
- (BOOL)isPath;

/// Returns whether the union's current tag state has value `Other`.
- (BOOL)isOther;

/// Returns a human-readable string representing the union's current tag state.
- (NSString * _Nonnull)getTagName;

@end


/// 
/// The serialization class for the `DBXFILESDownloadError` union.
/// 
@interface DBXFILESDownloadErrorSerializer : NSObject 

/// Returns a json-compatible dictionary representation of the
/// `DBXFILESDownloadError` object from an instantiation.
+ (NSDictionary * _Nonnull)serialize:(DBXFILESDownloadError * _Nonnull)obj;

/// Returns an instantiation of the `DBXFILESDownloadError` object from a
/// json-compatible dictionary representation.
+ (DBXFILESDownloadError * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
