///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXFILESLookupError;

/// 
/// The `DBXFILESLookupError` union.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXFILESLookupError : NSObject <DBXSerializable> 

/// The `DBXFILESLookupErrorTag` enum type represents the possible tag states
/// that the `DBXFILESLookupError` union can exist in.
typedef NS_ENUM(NSInteger, DBXFILESLookupErrorTag) {
    /// (no description).
    DBXFILESLookupErrorMalformedPath,

    /// There is nothing at the given path.
    DBXFILESLookupErrorNotFound,

    /// We were expecting a file, but the given path refers to something that
    /// isn't a file.
    DBXFILESLookupErrorNotFile,

    /// We were expecting a folder, but the given path refers to something that
    /// isn't a folder.
    DBXFILESLookupErrorNotFolder,

    /// The file cannot be transferred because the content is restricted.  For
    /// example, sometimes there are legal restrictions due to copyright claims.
    DBXFILESLookupErrorRestrictedContent,

    /// (no description).
    DBXFILESLookupErrorOther,

};

/// Represents the union's current tag state.
@property (nonatomic) DBXFILESLookupErrorTag tag;

/// (no description).
@property (nonatomic, copy) NSString * _Nullable malformedPath;

/// Initializes union class with tag state of `MalformedPath`.
- (nonnull instancetype)initWithMalformedPath:(NSString * _Nullable)malformedPath;

/// Initializes union class with tag state of `NotFound`.
- (nonnull instancetype)initWithNotFound;

/// Initializes union class with tag state of `NotFile`.
- (nonnull instancetype)initWithNotFile;

/// Initializes union class with tag state of `NotFolder`.
- (nonnull instancetype)initWithNotFolder;

/// Initializes union class with tag state of `RestrictedContent`.
- (nonnull instancetype)initWithRestrictedContent;

/// Initializes union class with tag state of `Other`.
- (nonnull instancetype)initWithOther;

/// Returns whether the union's current tag state has value `MalformedPath`.
- (BOOL)isMalformedPath;

/// Returns whether the union's current tag state has value `NotFound`.
- (BOOL)isNotFound;

/// Returns whether the union's current tag state has value `NotFile`.
- (BOOL)isNotFile;

/// Returns whether the union's current tag state has value `NotFolder`.
- (BOOL)isNotFolder;

/// Returns whether the union's current tag state has value `RestrictedContent`.
- (BOOL)isRestrictedContent;

/// Returns whether the union's current tag state has value `Other`.
- (BOOL)isOther;

/// Returns a human-readable string representing the union's current tag state.
- (NSString * _Nonnull)getTagName;

/// Returns a human-readable representation of the `DBXFILESLookupError` object.
- (NSString * _Nonnull)description;

@end


/// 
/// The serialization class for the `DBXFILESLookupError` union.
/// 
@interface DBXFILESLookupErrorSerializer : NSObject 

/// Returns a json-compatible dictionary representation of the
/// `DBXFILESLookupError` object from an instantiation.
+ (NSDictionary * _Nonnull)serialize:(DBXFILESLookupError * _Nonnull)obj;

/// Returns an instantiation of the `DBXFILESLookupError` object from a
/// json-compatible dictionary representation.
+ (DBXFILESLookupError * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
