///
/// Auto-generated by Stone, do not modify.
///

#import "DBXFILESFileSharingInfo.h"
#import "DBXFILESSharingInfo.h"
#import "DBXStoneSerializers.h"
#import "DBXStoneValidators.h"

@implementation DBXFILESFileSharingInfo 

- (instancetype)initWithReadOnly:(NSNumber *)readOnly parentSharedFolderId:(NSString *)parentSharedFolderId modifiedBy:(NSString *)modifiedBy {
    [DBXStoneValidators stringValidator:nil maxLength:nil pattern:@"[-_0-9a-zA-Z:]+"](parentSharedFolderId);
    [DBXStoneValidators nullableValidator:[DBXStoneValidators stringValidator:@(40) maxLength:@(40) pattern:nil]](modifiedBy);

    self = [super initWithReadOnly:readOnly];
    if (self != nil) {
        _parentSharedFolderId = parentSharedFolderId;
        _modifiedBy = modifiedBy;
    }
    return self;
}

- (instancetype)initWithReadOnly:(NSNumber *)readOnly parentSharedFolderId:(NSString *)parentSharedFolderId {
    return [self initWithReadOnly:readOnly parentSharedFolderId:parentSharedFolderId modifiedBy:nil];
}

+ (NSDictionary *)serialize:(id)obj {
    return [DBXFILESFileSharingInfoSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DBXFILESFileSharingInfoSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DBXFILESFileSharingInfoSerializer serialize:self] description];
}

@end


@implementation DBXFILESFileSharingInfoSerializer 

+ (NSDictionary *)serialize:(DBXFILESFileSharingInfo *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    jsonDict[@"read_only"] = valueObj.readOnly;
    jsonDict[@"parent_shared_folder_id"] = valueObj.parentSharedFolderId;
    if (valueObj.modifiedBy) {
        jsonDict[@"modified_by"] = valueObj.modifiedBy;
    }

    return jsonDict;
}

+ (DBXFILESFileSharingInfo *)deserialize:(NSDictionary *)valueDict {
    NSNumber *readOnly = valueDict[@"read_only"];
    NSString *parentSharedFolderId = valueDict[@"parent_shared_folder_id"];
    NSString *modifiedBy = valueDict[@"modified_by"] ?: nil;

    return [[DBXFILESFileSharingInfo alloc] initWithReadOnly:readOnly parentSharedFolderId:parentSharedFolderId modifiedBy:modifiedBy];
}

@end
