///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXPROPERTIESGetPropertyTemplateArg;

/// 
/// The GetPropertyTemplateArg struct.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXPROPERTIESGetPropertyTemplateArg : NSObject <DBXSerializable> 

/// An identifier for property template added by route properties/template/add.
@property (nonatomic, readonly, copy) NSString * _Nonnull templateId;

/// 
/// Full constructor for the `DBXPROPERTIESGetPropertyTemplateArg` struct
/// (exposes all instance variables).
/// 
/// - parameter templateId: An identifier for property template added by route
/// properties/template/add.
/// 
/// - returns: An initialized `DBXPROPERTIESGetPropertyTemplateArg` instance.
/// 
- (nonnull instancetype)initWithTemplateId:(NSString * _Nonnull)templateId;

@end


/// 
/// The serialization class for the GetPropertyTemplateArg struct.
/// 
@interface DBXPROPERTIESGetPropertyTemplateArgSerializer : NSObject 

/// 
/// Serializes `DBXPROPERTIESGetPropertyTemplateArg` instances.
/// 
///  - parameter instance: An instance of the
/// `DBXPROPERTIESGetPropertyTemplateArg` API object.
/// 
///  - returns: A json-compatible dictionary representation of the
/// `DBXPROPERTIESGetPropertyTemplateArg` API object.
/// 
+ (NSDictionary * _Nonnull)serialize:(DBXPROPERTIESGetPropertyTemplateArg * _Nonnull)instance;

/// 
/// Deserializes `DBXPROPERTIESGetPropertyTemplateArg` instances.
/// 
///  - parameter dict: A json-compatible dictionary representation of the
/// `DBXPROPERTIESGetPropertyTemplateArg` API object.
/// 
///  - returns: An instantiation of the `DBXPROPERTIESGetPropertyTemplateArg`
/// object.
/// 
+ (DBXPROPERTIESGetPropertyTemplateArg * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
