///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXPROPERTIESPropertyType;

/// 
/// The `DBXPROPERTIESPropertyType` union.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
/// Data type of the given property added. This endpoint is in beta and  only
/// properties of type strings is supported.
/// 
@interface DBXPROPERTIESPropertyType : NSObject <DBXSerializable> 

/// The `DBXPROPERTIESPropertyTypeTag` enum type represents the possible tag
/// states that the `DBXPROPERTIESPropertyType` union can exist in.
typedef NS_ENUM(NSInteger, DBXPROPERTIESPropertyTypeTag) {
    /// The associated property will be of type string. Unicode is supported.
    DBXPROPERTIESPropertyTypeString,

    /// (no description).
    DBXPROPERTIESPropertyTypeOther,

};

/// Represents the union's current tag state.
@property (nonatomic) DBXPROPERTIESPropertyTypeTag tag;

/// Initializes union class with tag state of `String`.
- (nonnull instancetype)initWithString;

/// Initializes union class with tag state of `Other`.
- (nonnull instancetype)initWithOther;

/// Returns whether the union's current tag state has value `String`.
- (BOOL)isString;

/// Returns whether the union's current tag state has value `Other`.
- (BOOL)isOther;

/// Returns a human-readable string representing the union's current tag state.
- (NSString * _Nonnull)getTagName;

/// Returns a human-readable representation of the `DBXPROPERTIESPropertyType`
/// object.
- (NSString * _Nonnull)description;

@end


/// 
/// The serialization class for the `DBXPROPERTIESPropertyType` union.
/// 
@interface DBXPROPERTIESPropertyTypeSerializer : NSObject 

/// Returns a json-compatible dictionary representation of the
/// `DBXPROPERTIESPropertyType` object from an instantiation.
+ (NSDictionary * _Nonnull)serialize:(DBXPROPERTIESPropertyType * _Nonnull)obj;

/// Returns an instantiation of the `DBXPROPERTIESPropertyType` object from a
/// json-compatible dictionary representation.
+ (DBXPROPERTIESPropertyType * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
