///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXSHARINGJobError;
@class DBXSHARINGRelinquishFolderMembershipError;
@class DBXSHARINGRemoveFolderMemberError;
@class DBXSHARINGUnshareFolderError;

/// 
/// The `DBXSHARINGJobError` union.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
/// Error occurred while performing an asynchronous job from unshareFolder or
/// removeFolderMember.
/// 
@interface DBXSHARINGJobError : NSObject <DBXSerializable> 

/// The `DBXSHARINGJobErrorTag` enum type represents the possible tag states
/// that the `DBXSHARINGJobError` union can exist in.
typedef NS_ENUM(NSInteger, DBXSHARINGJobErrorTag) {
    /// Error occurred while performing unshareFolder action.
    DBXSHARINGJobErrorUnshareFolderError,

    /// Error occurred while performing removeFolderMember action.
    DBXSHARINGJobErrorRemoveFolderMemberError,

    /// Error occurred while performing relinquishFolderMembership action.
    DBXSHARINGJobErrorRelinquishFolderMembershipError,

    /// (no description).
    DBXSHARINGJobErrorOther,

};

/// Represents the union's current tag state.
@property (nonatomic, readonly) DBXSHARINGJobErrorTag tag;

/// Error occurred while performing unshareFolder action.
@property (nonatomic, readonly) DBXSHARINGUnshareFolderError * _Nonnull unshareFolderError;

/// Error occurred while performing removeFolderMember action.
@property (nonatomic, readonly) DBXSHARINGRemoveFolderMemberError * _Nonnull removeFolderMemberError;

/// Error occurred while performing relinquishFolderMembership action.
@property (nonatomic, readonly) DBXSHARINGRelinquishFolderMembershipError * _Nonnull relinquishFolderMembershipError;

/// Initializes union class with tag state of `UnshareFolderError`.
- (nonnull instancetype)initWithUnshareFolderError:(DBXSHARINGUnshareFolderError * _Nonnull)unshareFolderError;

/// Initializes union class with tag state of `RemoveFolderMemberError`.
- (nonnull instancetype)initWithRemoveFolderMemberError:(DBXSHARINGRemoveFolderMemberError * _Nonnull)removeFolderMemberError;

/// Initializes union class with tag state of `RelinquishFolderMembershipError`.
- (nonnull instancetype)initWithRelinquishFolderMembershipError:(DBXSHARINGRelinquishFolderMembershipError * _Nonnull)relinquishFolderMembershipError;

/// Initializes union class with tag state of `Other`.
- (nonnull instancetype)initWithOther;

/// Returns whether the union's current tag state has value
/// `UnshareFolderError`.
- (BOOL)isUnshareFolderError;

/// Returns whether the union's current tag state has value
/// `RemoveFolderMemberError`.
- (BOOL)isRemoveFolderMemberError;

/// Returns whether the union's current tag state has value
/// `RelinquishFolderMembershipError`.
- (BOOL)isRelinquishFolderMembershipError;

/// Returns whether the union's current tag state has value `Other`.
- (BOOL)isOther;

/// Returns a human-readable string representing the union's current tag state.
- (NSString * _Nonnull)getTagName;

@end


/// 
/// The serialization class for the `DBXSHARINGJobError` union.
/// 
@interface DBXSHARINGJobErrorSerializer : NSObject 

/// Returns a json-compatible dictionary representation of the
/// `DBXSHARINGJobError` object from an instantiation.
+ (NSDictionary * _Nonnull)serialize:(DBXSHARINGJobError * _Nonnull)obj;

/// Returns an instantiation of the `DBXSHARINGJobError` object from a
/// json-compatible dictionary representation.
+ (DBXSHARINGJobError * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
