///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXSHARINGMemberPermission;
@class DBXSHARINGParentFolderAccessInfo;

/// 
/// The ParentFolderAccessInfo struct.
/// 
/// Contains information about a parent folder that a member has access to.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXSHARINGParentFolderAccessInfo : NSObject <DBXSerializable> 

/// Display name for the folder.
@property (nonatomic, readonly, copy) NSString * _Nonnull folderName;

/// The identifier of the parent shared folder.
@property (nonatomic, readonly, copy) NSString * _Nonnull sharedFolderId;

/// The user's permissions for the parent shared folder.
@property (nonatomic, readonly) NSArray<DBXSHARINGMemberPermission *> * _Nonnull permissions;

/// 
/// Full constructor for the `DBXSHARINGParentFolderAccessInfo` struct (exposes
/// all instance variables).
/// 
/// - parameter folderName: Display name for the folder.
/// - parameter sharedFolderId: The identifier of the parent shared folder.
/// - parameter permissions: The user's permissions for the parent shared
/// folder.
/// 
/// - returns: An initialized `DBXSHARINGParentFolderAccessInfo` instance.
/// 
- (nonnull instancetype)initWithFolderName:(NSString * _Nonnull)folderName sharedFolderId:(NSString * _Nonnull)sharedFolderId permissions:(NSArray<DBXSHARINGMemberPermission *> * _Nonnull)permissions;

@end


/// 
/// The serialization class for the ParentFolderAccessInfo struct.
/// 
@interface DBXSHARINGParentFolderAccessInfoSerializer : NSObject 

/// 
/// Serializes `DBXSHARINGParentFolderAccessInfo` instances.
/// 
///  - parameter instance: An instance of the `DBXSHARINGParentFolderAccessInfo`
/// API object.
/// 
///  - returns: A json-compatible dictionary representation of the
/// `DBXSHARINGParentFolderAccessInfo` API object.
/// 
+ (NSDictionary * _Nonnull)serialize:(DBXSHARINGParentFolderAccessInfo * _Nonnull)instance;

/// 
/// Deserializes `DBXSHARINGParentFolderAccessInfo` instances.
/// 
///  - parameter dict: A json-compatible dictionary representation of the
/// `DBXSHARINGParentFolderAccessInfo` API object.
/// 
///  - returns: An instantiation of the `DBXSHARINGParentFolderAccessInfo`
/// object.
/// 
+ (DBXSHARINGParentFolderAccessInfo * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
