///
/// Auto-generated by Stone, do not modify.
///

#import "DbxSharingRevokeSharedLinkArg.h"
#import "DbxStoneSerializers.h"
#import "DbxStoneValidators.h"

@implementation DbxSharingRevokeSharedLinkArg 

- (instancetype)initWithUrl:(NSString *)url {

    self = [super init];
    if (self != nil) {
        _url = url;
    }
    return self;
}

+ (NSDictionary *)serialize:(id)obj {
    return [DbxSharingRevokeSharedLinkArgSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DbxSharingRevokeSharedLinkArgSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DbxSharingRevokeSharedLinkArgSerializer serialize:self] description];
}

@end


@implementation DbxSharingRevokeSharedLinkArgSerializer 

+ (NSDictionary *)serialize:(DbxSharingRevokeSharedLinkArg *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    jsonDict[@"url"] = valueObj.url;

    return jsonDict;
}

+ (DbxSharingRevokeSharedLinkArg *)deserialize:(NSDictionary *)valueDict {
    NSString *url = valueDict[@"url"];

    return [[DbxSharingRevokeSharedLinkArg alloc] initWithUrl:url];
}

@end
