///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXSHARINGMemberPolicy;

/// 
/// The MemberPolicy union.
/// 
/// Policy governing who can be a member of a shared folder. Only applicable to
/// folders owned by a user on a team.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXSHARINGMemberPolicy : NSObject <DBXSerializable> 

/// The `DBXSHARINGMemberPolicyTag` enum type represents the possible tag states
/// with which the `DBXSHARINGMemberPolicy` union can exist.
typedef NS_ENUM(NSInteger, DBXSHARINGMemberPolicyTag) {
    /// Only a teammate can become a member.
    DBXSHARINGMemberPolicyTeam,

    /// Anyone can become a member.
    DBXSHARINGMemberPolicyAnyone,

    /// (no description).
    DBXSHARINGMemberPolicyOther,

};

/// Represents the union's current tag state.
@property (nonatomic, readonly) DBXSHARINGMemberPolicyTag tag;

/// 
/// Initializes union class with tag state of `Team`.
/// 
/// About the `Team` tag state: Only a teammate can become a member.
/// 
/// - returns: An initialized `DBXSHARINGMemberPolicy` instance.
/// 
- (nonnull instancetype)initWithTeam;

/// 
/// Initializes union class with tag state of `Anyone`.
/// 
/// About the `Anyone` tag state: Anyone can become a member.
/// 
/// - returns: An initialized `DBXSHARINGMemberPolicy` instance.
/// 
- (nonnull instancetype)initWithAnyone;

/// 
/// Initializes union class with tag state of `Other`.
/// 
/// - returns: An initialized `DBXSHARINGMemberPolicy` instance.
/// 
- (nonnull instancetype)initWithOther;

/// 
/// Retrieves whether the union's current tag state has value `Team`.
/// 
/// - returns: Whether the union's current tag state has value `Team`.
/// 
- (BOOL)isTeam;

/// 
/// Retrieves whether the union's current tag state has value `Anyone`.
/// 
/// - returns: Whether the union's current tag state has value `Anyone`.
/// 
- (BOOL)isAnyone;

/// 
/// Retrieves whether the union's current tag state has value `Other`.
/// 
/// - returns: Whether the union's current tag state has value `Other`.
/// 
- (BOOL)isOther;

/// 
/// Retrieves string value of union's current tag state.
/// 
/// - returns: A human-readable string representing the union's current tag
/// state.
/// 
- (NSString * _Nonnull)getTagName;

@end


/// 
/// The serialization class for the `DBXSHARINGMemberPolicy` union.
/// 
@interface DBXSHARINGMemberPolicySerializer : NSObject 

/// 
/// Serializes `DBXSHARINGMemberPolicy` instances.
/// 
///  - parameter instance: An instance of the `DBXSHARINGMemberPolicy` API
/// object.
/// 
///  - returns: A json-compatible dictionary representation of the
/// `DBXSHARINGMemberPolicy` API object.
/// 
+ (NSDictionary * _Nonnull)serialize:(DBXSHARINGMemberPolicy * _Nonnull)instance;

/// 
/// Deserializes `DBXSHARINGMemberPolicy` instances.
/// 
///  - parameter dict: A json-compatible dictionary representation of the
/// `DBXSHARINGMemberPolicy` API object.
/// 
///  - returns: An instantiation of the `DBXSHARINGMemberPolicy` object.
/// 
+ (DBXSHARINGMemberPolicy * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
