///
/// Auto-generated by Stone, do not modify.
///

#import "DBXSHARINGAccessLevel.h"
#import "DBXSHARINGChangeFileMemberAccessArgs.h"
#import "DBXSHARINGMemberSelector.h"
#import "DBXStoneSerializers.h"
#import "DBXStoneValidators.h"

@implementation DBXSHARINGChangeFileMemberAccessArgs 

- (instancetype)initWithFile:(NSString *)file member:(DBXSHARINGMemberSelector *)member accessLevel:(DBXSHARINGAccessLevel *)accessLevel {
    [DBXStoneValidators stringValidator:[NSNumber numberWithInt:1] maxLength:nil pattern:@"((/|id:).*|nspath:[^:]*:[^:]*)"](file);

    self = [super init];
    if (self != nil) {
        _file = file;
        _member = member;
        _accessLevel = accessLevel;
    }
    return self;
}

+ (NSDictionary *)serialize:(id)obj {
    return [DBXSHARINGChangeFileMemberAccessArgsSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DBXSHARINGChangeFileMemberAccessArgsSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DBXSHARINGChangeFileMemberAccessArgsSerializer serialize:self] description];
}

@end


@implementation DBXSHARINGChangeFileMemberAccessArgsSerializer 

+ (NSDictionary *)serialize:(DBXSHARINGChangeFileMemberAccessArgs *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    jsonDict[@"file"] = valueObj.file;
    jsonDict[@"member"] = [DBXSHARINGMemberSelectorSerializer serialize:valueObj.member];
    jsonDict[@"access_level"] = [DBXSHARINGAccessLevelSerializer serialize:valueObj.accessLevel];

    return jsonDict;
}

+ (DBXSHARINGChangeFileMemberAccessArgs *)deserialize:(NSDictionary *)valueDict {
    NSString *file = valueDict[@"file"];
    DBXSHARINGMemberSelector *member = [DBXSHARINGMemberSelectorSerializer deserialize:valueDict[@"member"]];
    DBXSHARINGAccessLevel *accessLevel = [DBXSHARINGAccessLevelSerializer deserialize:valueDict[@"access_level"]];

    return [[DBXSHARINGChangeFileMemberAccessArgs alloc] initWithFile:file member:member accessLevel:accessLevel];
}

@end
