///
/// Auto-generated by Stone, do not modify.
///

#import "DbxAsyncPollResultBase.h"
#import "DbxSharingJobError.h"
#import "DbxSharingJobStatus.h"
#import "DbxStoneSerializers.h"
#import "DbxStoneValidators.h"

@implementation DbxSharingJobStatus 

- (instancetype)initWithInProgress {
    self = [super init];
    if (self != nil) {
        _tag = (SharingJobStatusTag)SharingJobStatusInProgress;
    }
    return self;
}

- (instancetype)initWithComplete {
    self = [super init];
    if (self != nil) {
        _tag = (SharingJobStatusTag)SharingJobStatusComplete;
    }
    return self;
}

- (instancetype)initWithFailed:(DbxSharingJobError *)failed {
    self = [super init];
    if (self != nil) {
        _tag = (SharingJobStatusTag)SharingJobStatusFailed;
        _failed = failed;
    }
    return self;
}

- (BOOL)isInProgress {
    return _tag == (SharingJobStatusTag)SharingJobStatusInProgress;
}

- (BOOL)isComplete {
    return _tag == (SharingJobStatusTag)SharingJobStatusComplete;
}

- (BOOL)isFailed {
    return _tag == (SharingJobStatusTag)SharingJobStatusFailed;
}

- (NSString *)getTagName {
    if (_tag == (SharingJobStatusTag)SharingJobStatusInProgress) {
        return @"(SharingJobStatusTag)SharingJobStatusInProgress";
    }
    if (_tag == (SharingJobStatusTag)SharingJobStatusComplete) {
        return @"(SharingJobStatusTag)SharingJobStatusComplete";
    }
    if (_tag == (SharingJobStatusTag)SharingJobStatusFailed) {
        return @"(SharingJobStatusTag)SharingJobStatusFailed";
    }

    @throw([NSException exceptionWithName:@"InvalidTagEnum" reason:@"Supplied tag enum has an invalid value." userInfo:nil]);
}

- (DbxSharingJobError *)failed {
    if (_tag != (SharingJobStatusTag)SharingJobStatusFailed) {
        [NSException raise:@"IllegalStateException" format:@"Invalid tag: required (SharingJobStatusTag)SharingJobStatusFailed, but was %@.", [self getTagName]];
    }
    return _failed;
}

+ (NSDictionary *)serialize:(id)obj {
    return [DbxSharingJobStatusSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DbxSharingJobStatusSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DbxSharingJobStatusSerializer serialize:self] description];
}

@end


@implementation DbxSharingJobStatusSerializer 

+ (NSDictionary *)serialize:(DbxSharingJobStatus *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    if ([valueObj isInProgress]) {
        jsonDict[@".tag"] = @"in_progress";
    }
    else if ([valueObj isComplete]) {
        jsonDict[@".tag"] = @"complete";
    }
    else if ([valueObj isFailed]) {
        jsonDict = [[DbxSharingJobErrorSerializer serialize:valueObj.failed] mutableCopy];
        jsonDict[@".tag"] = @"failed";
    }
    else {
        @throw([NSException exceptionWithName:@"InvalidTagEnum" reason:@"Supplied tag enum has an invalid value." userInfo:nil]);
    }

    return jsonDict;
}

+ (DbxSharingJobStatus *)deserialize:(NSDictionary *)valueDict {
    NSString *tag = valueDict[@".tag"];

    if ([tag isEqualToString:@"in_progress"]) {
        return [[DbxSharingJobStatus alloc] initWithInProgress];
    }
    if ([tag isEqualToString:@"complete"]) {
        return [[DbxSharingJobStatus alloc] initWithComplete];
    }
    if ([tag isEqualToString:@"failed"]) {
        DbxSharingJobError *failed = [DbxSharingJobErrorSerializer deserialize:valueDict[@"failed"]];
        return [[DbxSharingJobStatus alloc] initWithFailed:failed];
    }

    @throw([NSException exceptionWithName:@"InvalidTagEnum" reason:@"Supplied tag enum has an invalid value." userInfo:nil]);
}

@end
