///
/// Auto-generated by Stone, do not modify.
///

#import "DbxSharingListFileMembersBatchResult.h"
#import "DbxSharingListFileMembersIndividualResult.h"
#import "DbxStoneSerializers.h"
#import "DbxStoneValidators.h"

@implementation DbxSharingListFileMembersBatchResult 

- (instancetype)initWithFile:(NSString *)file result:(DbxSharingListFileMembersIndividualResult *)result {
    [DbxStoneValidators stringValidator:[NSNumber numberWithInt:1] maxLength:nil pattern:@"((/|id:).*|nspath:[^:]*:[^:]*)"](file);

    self = [super init];
    if (self != nil) {
        _file = file;
        _result = result;
    }
    return self;
}

+ (NSDictionary *)serialize:(id)obj {
    return [DbxSharingListFileMembersBatchResultSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DbxSharingListFileMembersBatchResultSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DbxSharingListFileMembersBatchResultSerializer serialize:self] description];
}

@end


@implementation DbxSharingListFileMembersBatchResultSerializer 

+ (NSDictionary *)serialize:(DbxSharingListFileMembersBatchResult *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    jsonDict[@"file"] = valueObj.file;
    jsonDict[@"result"] = [DbxSharingListFileMembersIndividualResultSerializer serialize:valueObj.result];

    return jsonDict;
}

+ (DbxSharingListFileMembersBatchResult *)deserialize:(NSDictionary *)valueDict {
    NSString *file = valueDict[@"file"];
    DbxSharingListFileMembersIndividualResult *result = [DbxSharingListFileMembersIndividualResultSerializer deserialize:valueDict[@"result"]];

    return [[DbxSharingListFileMembersBatchResult alloc] initWithFile:file result:result];
}

@end
