///
/// Auto-generated by Stone, do not modify.
///

#import "DbxSharingListFileMembersArg.h"
#import "DbxSharingMemberAction.h"
#import "DbxStoneSerializers.h"
#import "DbxStoneValidators.h"

@implementation DbxSharingListFileMembersArg 

- (instancetype)initWithFile:(NSString *)file actions:(NSArray<DbxSharingMemberAction *> *)actions includeInherited:(NSNumber *)includeInherited limit:(NSNumber *)limit {
    [DbxStoneValidators stringValidator:[NSNumber numberWithInt:1] maxLength:nil pattern:@"((/|id:).*|nspath:[^:]*:[^:]*)"](file);
    [DbxStoneValidators nullableValidator:[DbxStoneValidators arrayValidator:nil maxItems:nil itemValidator:nil]](actions);
    [DbxStoneValidators numericValidator:[NSNumber numberWithInt:1] maxValue:[NSNumber numberWithInt:300]](limit ?: [NSNumber numberWithInt:100]);

    self = [super init];
    if (self != nil) {
        _file = file;
        _actions = actions;
        _includeInherited = includeInherited ?: @YES;
        _limit = limit ?: [NSNumber numberWithInt:100];
    }
    return self;
}

- (instancetype)initWithFile:(NSString *)file {
    return [self initWithFile:file actions:nil includeInherited:nil limit:nil];
}

+ (NSDictionary *)serialize:(id)obj {
    return [DbxSharingListFileMembersArgSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DbxSharingListFileMembersArgSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DbxSharingListFileMembersArgSerializer serialize:self] description];
}

@end


@implementation DbxSharingListFileMembersArgSerializer 

+ (NSDictionary *)serialize:(DbxSharingListFileMembersArg *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    jsonDict[@"file"] = [DbxStringSerializer serialize:valueObj.file];
    if (valueObj.actions != nil) {
        jsonDict[@"actions"] = [DbxArraySerializer serialize:valueObj.actions withBlock:^id(id obj) { return [DbxSharingMemberActionSerializer serialize:obj]; }];
    }
    jsonDict[@"include_inherited"] = [DbxBoolSerializer serialize:valueObj.includeInherited];
    jsonDict[@"limit"] = [DbxNSNumberSerializer serialize:valueObj.limit];

    return jsonDict;
}

+ (DbxSharingListFileMembersArg *)deserialize:(NSDictionary *)valueDict {
    NSString *file = [DbxStringSerializer deserialize:valueDict];
    NSArray<DbxSharingMemberAction *> *actions = valueDict != nil ? [DbxArraySerializer deserialize:valueDict withBlock:^id(id obj) { return [DbxSharingMemberActionSerializer deserialize:obj]; }] : nil;
    NSNumber *includeInherited = [DbxBoolSerializer deserialize:valueDict];
    NSNumber *limit = [DbxNSNumberSerializer deserialize:valueDict];

    return [[DbxSharingListFileMembersArg alloc] initWithFile:file actions:actions includeInherited:includeInherited limit:limit];
}

@end
