///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXSHARINGSharingUserError;

/// 
/// The `DBXSHARINGSharingUserError` union.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
/// User account had a problem preventing this action.
/// 
@interface DBXSHARINGSharingUserError : NSObject <DBXSerializable> 

/// The `DBXSHARINGSharingUserErrorTag` enum type represents the possible tag
/// states that the `DBXSHARINGSharingUserError` union can exist in.
typedef NS_ENUM(NSInteger, DBXSHARINGSharingUserErrorTag) {
    /// The current user must verify the account e-mail address before
    /// performing this action.
    DBXSHARINGSharingUserErrorEmailUnverified,

    /// (no description).
    DBXSHARINGSharingUserErrorOther,

};

/// Represents the union's current tag state.
@property (nonatomic, readonly) DBXSHARINGSharingUserErrorTag tag;

/// Initializes union class with tag state of `EmailUnverified`.
- (nonnull instancetype)initWithEmailUnverified;

/// Initializes union class with tag state of `Other`.
- (nonnull instancetype)initWithOther;

/// Returns whether the union's current tag state has value `EmailUnverified`.
- (BOOL)isEmailUnverified;

/// Returns whether the union's current tag state has value `Other`.
- (BOOL)isOther;

/// Returns a human-readable string representing the union's current tag state.
- (NSString * _Nonnull)getTagName;

@end


/// 
/// The serialization class for the `DBXSHARINGSharingUserError` union.
/// 
@interface DBXSHARINGSharingUserErrorSerializer : NSObject 

/// Returns a json-compatible dictionary representation of the
/// `DBXSHARINGSharingUserError` object from an instantiation.
+ (NSDictionary * _Nonnull)serialize:(DBXSHARINGSharingUserError * _Nonnull)obj;

/// Returns an instantiation of the `DBXSHARINGSharingUserError` object from a
/// json-compatible dictionary representation.
+ (DBXSHARINGSharingUserError * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
