///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXSHARINGInviteeInfo;

/// 
/// The `DBXSHARINGInviteeInfo` union.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
/// Information about the recipient of a shared content invitation.
/// 
@interface DBXSHARINGInviteeInfo : NSObject <DBXSerializable> 

/// The `DBXSHARINGInviteeInfoTag` enum type represents the possible tag states
/// that the `DBXSHARINGInviteeInfo` union can exist in.
typedef NS_ENUM(NSInteger, DBXSHARINGInviteeInfoTag) {
    /// E-mail address of invited user.
    DBXSHARINGInviteeInfoEmail,

    /// (no description).
    DBXSHARINGInviteeInfoOther,

};

/// Represents the union's current tag state.
@property (nonatomic, readonly) DBXSHARINGInviteeInfoTag tag;

/// E-mail address of invited user.
@property (nonatomic, readonly, copy) NSString * _Nonnull email;

/// Initializes union class with tag state of `Email`.
- (nonnull instancetype)initWithEmail:(NSString * _Nonnull)email;

/// Initializes union class with tag state of `Other`.
- (nonnull instancetype)initWithOther;

/// Returns whether the union's current tag state has value `Email`.
- (BOOL)isEmail;

/// Returns whether the union's current tag state has value `Other`.
- (BOOL)isOther;

/// Returns a human-readable string representing the union's current tag state.
- (NSString * _Nonnull)getTagName;

@end


/// 
/// The serialization class for the `DBXSHARINGInviteeInfo` union.
/// 
@interface DBXSHARINGInviteeInfoSerializer : NSObject 

/// Returns a json-compatible dictionary representation of the
/// `DBXSHARINGInviteeInfo` object from an instantiation.
+ (NSDictionary * _Nonnull)serialize:(DBXSHARINGInviteeInfo * _Nonnull)obj;

/// Returns an instantiation of the `DBXSHARINGInviteeInfo` object from a
/// json-compatible dictionary representation.
+ (DBXSHARINGInviteeInfo * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
