///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXSHARINGListFilesResult;
@class DBXSHARINGSharedFileMetadata;

/// 
/// The `DBXSHARINGListFilesResult` struct.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
/// Success results for listReceivedFiles.
/// 
@interface DBXSHARINGListFilesResult : NSObject <DBXSerializable> 

/// Information about the files shared with current user.
@property (nonatomic, readonly) NSArray<DBXSHARINGSharedFileMetadata *> * _Nonnull entries;

/// Cursor used to obtain additional shared files.
@property (nonatomic, readonly, copy) NSString * _Nullable cursor;

/// Full constructor for the `ListFilesResult` struct (exposes all instance
/// variables).
- (nonnull instancetype)initWithEntries:(NSArray<DBXSHARINGSharedFileMetadata *> * _Nonnull)entries cursor:(NSString * _Nullable)cursor;

/// Convenience constructor for the `ListFilesResult` struct (exposes only
/// non-nullable instance variables with no default value).
- (nonnull instancetype)initWithEntries:(NSArray<DBXSHARINGSharedFileMetadata *> * _Nonnull)entries;

@end


/// 
/// The serialization class for the `DBXSHARINGListFilesResult` struct.
/// 
@interface DBXSHARINGListFilesResultSerializer : NSObject 

/// Returns a json-compatible dictionary representation of the
/// `DBXSHARINGListFilesResult` object from an instantiation.
+ (NSDictionary * _Nonnull)serialize:(DBXSHARINGListFilesResult * _Nonnull)obj;

/// Returns an instantiation of the `DBXSHARINGListFilesResult` object from a
/// json-compatible dictionary representation.
+ (DBXSHARINGListFilesResult * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
