///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXSHARINGRelinquishFileMembershipError;
@class DBXSHARINGSharingFileAccessError;

/// 
/// The `DBXSHARINGRelinquishFileMembershipError` union.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXSHARINGRelinquishFileMembershipError : NSObject <DBXSerializable> 

/// The `DBXSHARINGRelinquishFileMembershipErrorTag` enum type represents the
/// possible tag states that the `DBXSHARINGRelinquishFileMembershipError` union
/// can exist in.
typedef NS_ENUM(NSInteger, DBXSHARINGRelinquishFileMembershipErrorTag) {
    /// (no description).
    DBXSHARINGRelinquishFileMembershipErrorAccessError,

    /// The current user has access to the shared file via a group.  You can't
    /// relinquish membership to a file shared via groups.
    DBXSHARINGRelinquishFileMembershipErrorGroupAccess,

    /// The current user does not have permission to perform this action.
    DBXSHARINGRelinquishFileMembershipErrorNoPermission,

    /// (no description).
    DBXSHARINGRelinquishFileMembershipErrorOther,

};

/// Represents the union's current tag state.
@property (nonatomic) DBXSHARINGRelinquishFileMembershipErrorTag tag;

/// (no description).
@property (nonatomic) DBXSHARINGSharingFileAccessError * _Nonnull accessError;

/// Initializes union class with tag state of `AccessError`.
- (nonnull instancetype)initWithAccessError:(DBXSHARINGSharingFileAccessError * _Nonnull)accessError;

/// Initializes union class with tag state of `GroupAccess`.
- (nonnull instancetype)initWithGroupAccess;

/// Initializes union class with tag state of `NoPermission`.
- (nonnull instancetype)initWithNoPermission;

/// Initializes union class with tag state of `Other`.
- (nonnull instancetype)initWithOther;

/// Returns whether the union's current tag state has value `AccessError`.
- (BOOL)isAccessError;

/// Returns whether the union's current tag state has value `GroupAccess`.
- (BOOL)isGroupAccess;

/// Returns whether the union's current tag state has value `NoPermission`.
- (BOOL)isNoPermission;

/// Returns whether the union's current tag state has value `Other`.
- (BOOL)isOther;

/// Returns a human-readable string representing the union's current tag state.
- (NSString * _Nonnull)getTagName;

/// Returns a human-readable representation of the
/// `DBXSHARINGRelinquishFileMembershipError` object.
- (NSString * _Nonnull)description;

@end


/// 
/// The serialization class for the `DBXSHARINGRelinquishFileMembershipError`
/// union.
/// 
@interface DBXSHARINGRelinquishFileMembershipErrorSerializer : NSObject 

/// Returns a json-compatible dictionary representation of the
/// `DBXSHARINGRelinquishFileMembershipError` object from an instantiation.
+ (NSDictionary * _Nonnull)serialize:(DBXSHARINGRelinquishFileMembershipError * _Nonnull)obj;

/// Returns an instantiation of the `DBXSHARINGRelinquishFileMembershipError`
/// object from a json-compatible dictionary representation.
+ (DBXSHARINGRelinquishFileMembershipError * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
