///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DbxStoneSerializers.h"
#import "DbxSharingRequestedVisibility.h"

@class DbxSharingResolvedVisibility;

/// 
/// The DbxSharingResolvedVisibility union.
/// 
/// The actual access permissions values of shared links after taking into
/// account user preferences and the team and shared folder settings. Check the
/// RequestedVisibility for more info on the possible visibility values that can
/// be set by the shared link's owner.
/// 
@interface DbxSharingResolvedVisibility : NSObject <DbxSerializable> 

typedef NS_ENUM(NSInteger, SharingResolvedVisibilityTag) {
    /// Anyone who has received the link can access it. No login required.
    SharingResolvedVisibilityPublic,
    /// Only members of the same team can access the link. Login is required.
    SharingResolvedVisibilityTeamOnly,
    /// A link-specific password is required to access the link. Login is not
    /// required.
    SharingResolvedVisibilityPassword,
    /// Only members of the same team who have the link-specific password can
    /// access the link. Login is required.
    SharingResolvedVisibilityTeamAndPassword,
    /// Only members of the shared folder containing the linked file can access
    /// the link. Login is required.
    SharingResolvedVisibilitySharedFolderOnly,
    /// (no description)
    SharingResolvedVisibilityOther,
};

- (nonnull instancetype)initWithPublic;

- (nonnull instancetype)initWithTeamOnly;

- (nonnull instancetype)initWithPassword;

- (nonnull instancetype)initWithTeamAndPassword;

- (nonnull instancetype)initWithSharedFolderOnly;

- (nonnull instancetype)initWithOther;

- (BOOL)isPublic;

- (BOOL)isTeamOnly;

- (BOOL)isPassword;

- (BOOL)isTeamAndPassword;

- (BOOL)isSharedFolderOnly;

- (BOOL)isOther;

- (NSString * _Nonnull)getTagName;

+ (NSDictionary * _Nonnull)serialize:(id _Nonnull)obj;

+ (id _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

- (NSString * _Nonnull)description;

/// Current state of the DbxSharingResolvedVisibility union type.
@property (nonatomic) SharingResolvedVisibilityTag tag;

@end


@interface DbxSharingResolvedVisibilitySerializer : NSObject 

+ (NSDictionary * _Nonnull)serialize:(DbxSharingResolvedVisibility * _Nonnull)obj;

+ (DbxSharingResolvedVisibility * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
