///
/// Auto-generated by Stone, do not modify.
///

#import "DbxSharingUserInfo.h"
#import "DbxStoneSerializers.h"
#import "DbxStoneValidators.h"

@implementation DbxSharingUserInfo 

- (instancetype)initWithAccountId:(NSString *)accountId sameTeam:(NSNumber *)sameTeam teamMemberId:(NSString *)teamMemberId {
    [DbxStoneValidators stringValidator:[NSNumber numberWithInt:40] maxLength:[NSNumber numberWithInt:40] pattern:nil](accountId);

    self = [super init];
    if (self != nil) {
        _accountId = accountId;
        _sameTeam = sameTeam;
        _teamMemberId = teamMemberId;
    }
    return self;
}

- (instancetype)initWithAccountId:(NSString *)accountId sameTeam:(NSNumber *)sameTeam {
    return [self initWithAccountId:accountId sameTeam:sameTeam teamMemberId:nil];
}

+ (NSDictionary *)serialize:(id)obj {
    return [DbxSharingUserInfoSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DbxSharingUserInfoSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DbxSharingUserInfoSerializer serialize:self] description];
}

@end


@implementation DbxSharingUserInfoSerializer 

+ (NSDictionary *)serialize:(DbxSharingUserInfo *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    jsonDict[@"account_id"] = valueObj.accountId;
    jsonDict[@"same_team"] = valueObj.sameTeam;
    if (valueObj.teamMemberId) {
        jsonDict[@"team_member_id"] = valueObj.teamMemberId;
    }

    return jsonDict;
}

+ (DbxSharingUserInfo *)deserialize:(NSDictionary *)valueDict {
    NSString *accountId = valueDict[@"account_id"];
    NSNumber *sameTeam = valueDict[@"same_team"];
    NSString *teamMemberId = valueDict[@"team_member_id"] ? valueDict[@"team_member_id"] : nil;

    return [[DbxSharingUserInfo alloc] initWithAccountId:accountId sameTeam:sameTeam teamMemberId:teamMemberId];
}

@end
