///
/// Auto-generated by Stone, do not modify.
///

#import "DbxSharingListSharedLinksArg.h"
#import "DbxStoneSerializers.h"
#import "DbxStoneValidators.h"

@implementation DbxSharingListSharedLinksArg 

- (instancetype)initWithPath:(NSString *)path cursor:(NSString *)cursor directOnly:(NSNumber *)directOnly {
    [DbxStoneValidators nullableValidator:[DbxStoneValidators stringValidator:nil maxLength:nil pattern:@"(/(.|[\\r\\n])*|id:.*)|(rev:[0-9a-f]{9,})|(ns:[0-9]+(/.*)?)"]](path);

    self = [super init];
    if (self != nil) {
        _path = path;
        _cursor = cursor;
        _directOnly = directOnly;
    }
    return self;
}

- (instancetype)init {
    return [self initWithPath:nil cursor:nil directOnly:nil];
}

+ (NSDictionary *)serialize:(id)obj {
    return [DbxSharingListSharedLinksArgSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DbxSharingListSharedLinksArgSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DbxSharingListSharedLinksArgSerializer serialize:self] description];
}

@end


@implementation DbxSharingListSharedLinksArgSerializer 

+ (NSDictionary *)serialize:(DbxSharingListSharedLinksArg *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    if (valueObj.path != nil) {
        jsonDict[@"path"] = [DbxStringSerializer serialize:valueObj.path];
    }
    if (valueObj.cursor != nil) {
        jsonDict[@"cursor"] = [DbxStringSerializer serialize:valueObj.cursor];
    }
    if (valueObj.directOnly != nil) {
        jsonDict[@"direct_only"] = [DbxBoolSerializer serialize:valueObj.directOnly];
    }

    return jsonDict;
}

+ (DbxSharingListSharedLinksArg *)deserialize:(NSDictionary *)valueDict {
    NSString *path = valueDict[@"path"] != nil ? [DbxStringSerializer deserialize:valueDict[@"path"]] : nil;
    NSString *cursor = valueDict[@"cursor"] != nil ? [DbxStringSerializer deserialize:valueDict[@"cursor"]] : nil;
    NSNumber *directOnly = valueDict[@"direct_only"] != nil ? [DbxBoolSerializer deserialize:valueDict[@"direct_only"]] : nil;

    return [[DbxSharingListSharedLinksArg alloc] initWithPath:path cursor:cursor directOnly:directOnly];
}

@end
