///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"
#import "DBXSHARINGMembershipInfo.h"

@class DBXSHARINGAccessLevel;
@class DBXSHARINGInviteeInfo;
@class DBXSHARINGInviteeMembershipInfo;
@class DBXSHARINGMemberPermission;
@class DBXSHARINGUserInfo;

/// 
/// The `DBXSHARINGInviteeMembershipInfo` struct.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
/// Information about an invited member of a shared content.
/// 
@interface DBXSHARINGInviteeMembershipInfo : DBXSHARINGMembershipInfo <DBXSerializable> 

/// Recipient of the invitation.
@property (nonatomic, readonly) DBXSHARINGInviteeInfo * _Nonnull invitee;

/// The user this invitation is tied to, if available.
@property (nonatomic, readonly) DBXSHARINGUserInfo * _Nullable user;

/// Full constructor for the `InviteeMembershipInfo` struct (exposes all
/// instance variables).
- (nonnull instancetype)initWithAccessType:(DBXSHARINGAccessLevel * _Nonnull)accessType invitee:(DBXSHARINGInviteeInfo * _Nonnull)invitee permissions:(NSArray<DBXSHARINGMemberPermission *> * _Nullable)permissions initials:(NSString * _Nullable)initials isInherited:(NSNumber * _Nullable)isInherited user:(DBXSHARINGUserInfo * _Nullable)user;

/// Convenience constructor for the `InviteeMembershipInfo` struct (exposes only
/// non-nullable instance variables with no default value).
- (nonnull instancetype)initWithAccessType:(DBXSHARINGAccessLevel * _Nonnull)accessType invitee:(DBXSHARINGInviteeInfo * _Nonnull)invitee;

@end


/// 
/// The serialization class for the `DBXSHARINGInviteeMembershipInfo` struct.
/// 
@interface DBXSHARINGInviteeMembershipInfoSerializer : NSObject 

/// Returns a json-compatible dictionary representation of the
/// `DBXSHARINGInviteeMembershipInfo` object from an instantiation.
+ (NSDictionary * _Nonnull)serialize:(DBXSHARINGInviteeMembershipInfo * _Nonnull)obj;

/// Returns an instantiation of the `DBXSHARINGInviteeMembershipInfo` object
/// from a json-compatible dictionary representation.
+ (DBXSHARINGInviteeMembershipInfo * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
