///
/// Auto-generated by Stone, do not modify.
///

#import "DbxSharingFileAction.h"
#import "DbxSharingGetFileMetadataArg.h"
#import "DbxStoneSerializers.h"
#import "DbxStoneValidators.h"

@implementation DbxSharingGetFileMetadataArg 

- (instancetype)initWithFile:(NSString *)file actions:(NSArray<DbxSharingFileAction *> *)actions {
    [DbxStoneValidators stringValidator:[NSNumber numberWithInt:1] maxLength:nil pattern:@"((/|id:).*|nspath:[^:]*:[^:]*)"](file);
    [DbxStoneValidators nullableValidator:[DbxStoneValidators arrayValidator:nil maxItems:nil itemValidator:nil]](actions);

    self = [super init];
    if (self != nil) {
        _file = file;
        _actions = actions;
    }
    return self;
}

- (instancetype)initWithFile:(NSString *)file {
    return [self initWithFile:file actions:nil];
}

+ (NSDictionary *)serialize:(id)obj {
    return [DbxSharingGetFileMetadataArgSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DbxSharingGetFileMetadataArgSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DbxSharingGetFileMetadataArgSerializer serialize:self] description];
}

@end


@implementation DbxSharingGetFileMetadataArgSerializer 

+ (NSDictionary *)serialize:(DbxSharingGetFileMetadataArg *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    jsonDict[@"file"] = [DbxStringSerializer serialize:valueObj.file];
    if (valueObj.actions != nil) {
        jsonDict[@"actions"] = [DbxArraySerializer serialize:valueObj.actions withBlock:^id(id obj) { return [DbxSharingFileActionSerializer serialize:obj]; }];
    }

    return jsonDict;
}

+ (DbxSharingGetFileMetadataArg *)deserialize:(NSDictionary *)valueDict {
    NSString *file = [DbxStringSerializer deserialize:valueDict];
    NSArray<DbxSharingFileAction *> *actions = valueDict != nil ? [DbxArraySerializer deserialize:valueDict withBlock:^id(id obj) { return [DbxSharingFileActionSerializer deserialize:obj]; }] : nil;

    return [[DbxSharingGetFileMetadataArg alloc] initWithFile:file actions:actions];
}

@end
