///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DbxStoneSerializers.h"

@class DbxSharingAclUpdatePolicy;
@class DbxSharingFolderPolicy;
@class DbxSharingMemberPolicy;
@class DbxSharingSharedLinkPolicy;

/// 
/// The DbxSharingFolderPolicy struct.
/// 
/// A set of policies governing membership and privileges for a shared folder.
/// 
@interface DbxSharingFolderPolicy : NSObject <DbxSerializable> 

/// Who can be a member of this shared folder, as set on the folder itself. The
/// effective policy may differ from this value if the team-wide policy is more
/// restrictive. Present only if the folder is owned by a team.
@property (nonatomic) DbxSharingMemberPolicy * _Nullable memberPolicy;
/// Who can be a member of this shared folder, taking into account both the
/// folder and the team-wide policy. This value may differ from that of
/// member_policy if the team-wide policy is more restrictive than the folder
/// policy. Present only if the folder is owned by a team.
@property (nonatomic) DbxSharingMemberPolicy * _Nullable resolvedMemberPolicy;
/// Who can add and remove members from this shared folder.
@property (nonatomic) DbxSharingAclUpdatePolicy * _Nonnull aclUpdatePolicy;
/// Who links can be shared with.
@property (nonatomic) DbxSharingSharedLinkPolicy * _Nonnull sharedLinkPolicy;

- (nonnull instancetype)initWithAclUpdatePolicy:(DbxSharingAclUpdatePolicy * _Nonnull)aclUpdatePolicy sharedLinkPolicy:(DbxSharingSharedLinkPolicy * _Nonnull)sharedLinkPolicy memberPolicy:(DbxSharingMemberPolicy * _Nullable)memberPolicy resolvedMemberPolicy:(DbxSharingMemberPolicy * _Nullable)resolvedMemberPolicy;

- (nonnull instancetype)initWithAclUpdatePolicy:(DbxSharingAclUpdatePolicy * _Nonnull)aclUpdatePolicy sharedLinkPolicy:(DbxSharingSharedLinkPolicy * _Nonnull)sharedLinkPolicy;

- (NSString * _Nonnull)description;

@end


@interface DbxSharingFolderPolicySerializer : NSObject 

+ (NSDictionary * _Nonnull)serialize:(DbxSharingFolderPolicy * _Nonnull)obj;

+ (DbxSharingFolderPolicy * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
