///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DbxStoneSerializers.h"

@class DbxSharingPermissionDeniedReason;

/// 
/// The DbxSharingPermissionDeniedReason union.
/// 
/// Possible reasons the user is denied a permission.
/// 
@interface DbxSharingPermissionDeniedReason : NSObject <DbxSerializable> 

typedef NS_ENUM(NSInteger, SharingPermissionDeniedReasonTag) {
    /// User is not on the same team as the folder owner.
    SharingPermissionDeniedReasonUserNotSameTeamAsOwner,
    /// User is prohibited by the owner from taking the action.
    SharingPermissionDeniedReasonUserNotAllowedByOwner,
    /// Target is indirectly a member of the folder, for example by being part
    /// of a group.
    SharingPermissionDeniedReasonTargetIsIndirectMember,
    /// Target is the owner of the folder.
    SharingPermissionDeniedReasonTargetIsOwner,
    /// Target is the user itself.
    SharingPermissionDeniedReasonTargetIsSelf,
    /// Target is not an active member of the team.
    SharingPermissionDeniedReasonTargetNotActive,
    /// Folder is team folder for a limited team.
    SharingPermissionDeniedReasonFolderIsLimitedTeamFolder,
    /// (no description)
    SharingPermissionDeniedReasonOther,
};

- (nonnull instancetype)initWithUserNotSameTeamAsOwner;

- (nonnull instancetype)initWithUserNotAllowedByOwner;

- (nonnull instancetype)initWithTargetIsIndirectMember;

- (nonnull instancetype)initWithTargetIsOwner;

- (nonnull instancetype)initWithTargetIsSelf;

- (nonnull instancetype)initWithTargetNotActive;

- (nonnull instancetype)initWithFolderIsLimitedTeamFolder;

- (nonnull instancetype)initWithOther;

- (BOOL)isUserNotSameTeamAsOwner;

- (BOOL)isUserNotAllowedByOwner;

- (BOOL)isTargetIsIndirectMember;

- (BOOL)isTargetIsOwner;

- (BOOL)isTargetIsSelf;

- (BOOL)isTargetNotActive;

- (BOOL)isFolderIsLimitedTeamFolder;

- (BOOL)isOther;

- (NSString * _Nonnull)getTagName;

+ (NSDictionary * _Nonnull)serialize:(id _Nonnull)obj;

+ (id _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

- (NSString * _Nonnull)description;

/// Current state of the DbxSharingPermissionDeniedReason union type.
@property (nonatomic) SharingPermissionDeniedReasonTag tag;

@end


@interface DbxSharingPermissionDeniedReasonSerializer : NSObject 

+ (NSDictionary * _Nonnull)serialize:(DbxSharingPermissionDeniedReason * _Nonnull)obj;

+ (DbxSharingPermissionDeniedReason * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
