///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXSHARINGGetSharedLinksArg;

/// 
/// The GetSharedLinksArg struct.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXSHARINGGetSharedLinksArg : NSObject <DBXSerializable> 

/// See getSharedLinks description.
@property (nonatomic, readonly, copy) NSString * _Nullable path;

/// 
/// Full constructor for the `DBXSHARINGGetSharedLinksArg` struct (exposes all
/// instance variables).
/// 
/// - parameter path: See :route:`get_shared_links` description.
/// 
/// - returns: An initialized `DBXSHARINGGetSharedLinksArg` instance.
/// 
- (nonnull instancetype)initWithPath:(NSString * _Nullable)path;

/// 
/// Convenience constructor for the `DBXSHARINGGetSharedLinksArg` struct
/// (exposes only non-nullable instance variables with no default value).
/// 
/// 
/// - returns: An initialized `DBXSHARINGGetSharedLinksArg` instance.
/// 
- (nonnull instancetype)init;

@end


/// 
/// The serialization class for the GetSharedLinksArg struct.
/// 
@interface DBXSHARINGGetSharedLinksArgSerializer : NSObject 

/// 
/// Serializes `DBXSHARINGGetSharedLinksArg` instances.
/// 
///  - parameter instance: An instance of the `DBXSHARINGGetSharedLinksArg` API
/// object.
/// 
///  - returns: A json-compatible dictionary representation of the
/// `DBXSHARINGGetSharedLinksArg` API object.
/// 
+ (NSDictionary * _Nonnull)serialize:(DBXSHARINGGetSharedLinksArg * _Nonnull)instance;

/// 
/// Deserializes `DBXSHARINGGetSharedLinksArg` instances.
/// 
///  - parameter dict: A json-compatible dictionary representation of the
/// `DBXSHARINGGetSharedLinksArg` API object.
/// 
///  - returns: An instantiation of the `DBXSHARINGGetSharedLinksArg` object.
/// 
+ (DBXSHARINGGetSharedLinksArg * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
