///
/// Auto-generated by Stone, do not modify.
///

#import "DbxSharingJobError.h"
#import "DbxSharingRelinquishFolderMembershipError.h"
#import "DbxSharingRemoveFolderMemberError.h"
#import "DbxSharingUnshareFolderError.h"
#import "DbxStoneSerializers.h"
#import "DbxStoneValidators.h"

@implementation DbxSharingJobError 

- (instancetype)initWithUnshareFolderError:(DbxSharingUnshareFolderError *)unshareFolderError {
    self = [super init];
    if (self != nil) {
        _tag = SharingJobErrorUnshareFolderError;
        _unshareFolderError = unshareFolderError;
    }
    return self;
}

- (instancetype)initWithRemoveFolderMemberError:(DbxSharingRemoveFolderMemberError *)removeFolderMemberError {
    self = [super init];
    if (self != nil) {
        _tag = SharingJobErrorRemoveFolderMemberError;
        _removeFolderMemberError = removeFolderMemberError;
    }
    return self;
}

- (instancetype)initWithRelinquishFolderMembershipError:(DbxSharingRelinquishFolderMembershipError *)relinquishFolderMembershipError {
    self = [super init];
    if (self != nil) {
        _tag = SharingJobErrorRelinquishFolderMembershipError;
        _relinquishFolderMembershipError = relinquishFolderMembershipError;
    }
    return self;
}

- (instancetype)initWithOther {
    self = [super init];
    if (self != nil) {
        _tag = SharingJobErrorOther;
    }
    return self;
}

- (BOOL)isUnshareFolderError {
    return _tag == SharingJobErrorUnshareFolderError;
}

- (BOOL)isRemoveFolderMemberError {
    return _tag == SharingJobErrorRemoveFolderMemberError;
}

- (BOOL)isRelinquishFolderMembershipError {
    return _tag == SharingJobErrorRelinquishFolderMembershipError;
}

- (BOOL)isOther {
    return _tag == SharingJobErrorOther;
}

- (NSString *)getTagName {
    switch (_tag) {
        case SharingJobErrorUnshareFolderError:
           return @"SharingJobErrorUnshareFolderError";
        case SharingJobErrorRemoveFolderMemberError:
           return @"SharingJobErrorRemoveFolderMemberError";
        case SharingJobErrorRelinquishFolderMembershipError:
           return @"SharingJobErrorRelinquishFolderMembershipError";
        case SharingJobErrorOther:
           return @"SharingJobErrorOther";
    }

    @throw([NSException exceptionWithName:@"InvalidTagEnum" reason:@"Supplied tag enum has an invalid value." userInfo:nil]);
}

- (DbxSharingUnshareFolderError *)unshareFolderError {
    if (_tag != SharingJobErrorUnshareFolderError) {
        [NSException raise:@"IllegalStateException" format:@"Invalid tag: required SharingJobErrorUnshareFolderError, but was %@.", [self getTagName]];
    }
    return _unshareFolderError;
}

- (DbxSharingRemoveFolderMemberError *)removeFolderMemberError {
    if (_tag != SharingJobErrorRemoveFolderMemberError) {
        [NSException raise:@"IllegalStateException" format:@"Invalid tag: required SharingJobErrorRemoveFolderMemberError, but was %@.", [self getTagName]];
    }
    return _removeFolderMemberError;
}

- (DbxSharingRelinquishFolderMembershipError *)relinquishFolderMembershipError {
    if (_tag != SharingJobErrorRelinquishFolderMembershipError) {
        [NSException raise:@"IllegalStateException" format:@"Invalid tag: required SharingJobErrorRelinquishFolderMembershipError, but was %@.", [self getTagName]];
    }
    return _relinquishFolderMembershipError;
}

+ (NSDictionary *)serialize:(id)obj {
    return [DbxSharingJobErrorSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DbxSharingJobErrorSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DbxSharingJobErrorSerializer serialize:self] description];
}

@end


@implementation DbxSharingJobErrorSerializer 

+ (NSDictionary *)serialize:(DbxSharingJobError *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    if ([valueObj isUnshareFolderError]) {
        jsonDict = [[DbxSharingUnshareFolderErrorSerializer serialize:valueObj.unshareFolderError] mutableCopy];
        jsonDict[@".tag"] = @"unshare_folder_error";
    }
    else if ([valueObj isRemoveFolderMemberError]) {
        jsonDict = [[DbxSharingRemoveFolderMemberErrorSerializer serialize:valueObj.removeFolderMemberError] mutableCopy];
        jsonDict[@".tag"] = @"remove_folder_member_error";
    }
    else if ([valueObj isRelinquishFolderMembershipError]) {
        jsonDict = [[DbxSharingRelinquishFolderMembershipErrorSerializer serialize:valueObj.relinquishFolderMembershipError] mutableCopy];
        jsonDict[@".tag"] = @"relinquish_folder_membership_error";
    }
    else if ([valueObj isOther]) {
        jsonDict[@".tag"] = @"other";
    }
    else {
        @throw([NSException exceptionWithName:@"InvalidTagEnum" reason:@"Supplied tag enum has an invalid value." userInfo:nil]);
    }

    return jsonDict;
}

+ (DbxSharingJobError *)deserialize:(NSDictionary *)valueDict {
    NSString *tag = valueDict[@".tag"];

    if ([tag isEqualToString:@"unshare_folder_error"]) {
        DbxSharingUnshareFolderError *unshareFolderError = [DbxSharingUnshareFolderErrorSerializer deserialize:valueDict[@"unshare_folder_error"]];
        return [[DbxSharingJobError alloc] initWithUnshareFolderError:unshareFolderError];
    }
    if ([tag isEqualToString:@"remove_folder_member_error"]) {
        DbxSharingRemoveFolderMemberError *removeFolderMemberError = [DbxSharingRemoveFolderMemberErrorSerializer deserialize:valueDict[@"remove_folder_member_error"]];
        return [[DbxSharingJobError alloc] initWithRemoveFolderMemberError:removeFolderMemberError];
    }
    if ([tag isEqualToString:@"relinquish_folder_membership_error"]) {
        DbxSharingRelinquishFolderMembershipError *relinquishFolderMembershipError = [DbxSharingRelinquishFolderMembershipErrorSerializer deserialize:valueDict[@"relinquish_folder_membership_error"]];
        return [[DbxSharingJobError alloc] initWithRelinquishFolderMembershipError:relinquishFolderMembershipError];
    }
    if ([tag isEqualToString:@"other"]) {
        return [[DbxSharingJobError alloc] initWithOther];
    }

    @throw([NSException exceptionWithName:@"InvalidTagEnum" reason:@"Supplied tag enum has an invalid value." userInfo:nil]);
}

@end
