///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DbxStoneSerializers.h"
#import "DbxSharingShareFolderErrorBase.h"

@class DbxSharingShareFolderError;
@class DbxSharingSharePathError;

/// 
/// The DbxSharingShareFolderError union.
/// 
@interface DbxSharingShareFolderError : NSObject <DbxSerializable> 

typedef NS_ENUM(NSInteger, SharingShareFolderErrorTag) {
    /// The current user's e-mail address is unverified.
    SharingShareFolderErrorEmailUnverified,
    /// path in ShareFolderArg is invalid.
    SharingShareFolderErrorBadPath,
    /// Team policy is more restrictive than memberPolicy in ShareFolderArg.
    SharingShareFolderErrorTeamPolicyDisallowsMemberPolicy,
    /// The current user's account is not allowed to select the specified
    /// sharedLinkPolicy in ShareFolderArg.
    SharingShareFolderErrorDisallowedSharedLinkPolicy,
    /// (no description)
    SharingShareFolderErrorOther,
    /// The current user does not have permission to perform this action.
    SharingShareFolderErrorNoPermission,
};

- (nonnull instancetype)initWithEmailUnverified;

- (nonnull instancetype)initWithBadPath:(DbxSharingSharePathError * _Nonnull)badPath;

- (nonnull instancetype)initWithTeamPolicyDisallowsMemberPolicy;

- (nonnull instancetype)initWithDisallowedSharedLinkPolicy;

- (nonnull instancetype)initWithOther;

- (nonnull instancetype)initWithNoPermission;

- (BOOL)isEmailUnverified;

- (BOOL)isBadPath;

- (BOOL)isTeamPolicyDisallowsMemberPolicy;

- (BOOL)isDisallowedSharedLinkPolicy;

- (BOOL)isOther;

- (BOOL)isNoPermission;

- (NSString * _Nonnull)getTagName;

- (NSString * _Nonnull)description;

/// Current state of the DbxSharingShareFolderError union type.
@property (nonatomic) SharingShareFolderErrorTag tag;
@property (nonatomic) DbxSharingSharePathError * _Nonnull badPath;

@end


@interface DbxSharingShareFolderErrorSerializer : NSObject 

+ (NSDictionary * _Nonnull)serialize:(DbxSharingShareFolderError * _Nonnull)obj;

+ (DbxSharingShareFolderError * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
