///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXSHARINGAccessLevel;
@class DBXSHARINGMemberPermission;
@class DBXSHARINGMembershipInfo;

/// 
/// The `DBXSHARINGMembershipInfo` struct.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
/// The information about a member of the shared content.
/// 
@interface DBXSHARINGMembershipInfo : NSObject <DBXSerializable> 

/// The access type for this member.
@property (nonatomic) DBXSHARINGAccessLevel * _Nonnull accessType;

/// The permissions that requesting user has on this member. The set of
/// permissions corresponds to the MemberActions in the request.
@property (nonatomic) NSArray<DBXSHARINGMemberPermission *> * _Nullable permissions;

/// Suggested name initials for a member.
@property (nonatomic, copy) NSString * _Nullable initials;

/// True if the member has access from a parent folder.
@property (nonatomic, copy) NSNumber * _Nonnull isInherited;

/// Full constructor for the `MembershipInfo` struct (exposes all instance
/// variables).
- (nonnull instancetype)initWithAccessType:(DBXSHARINGAccessLevel * _Nonnull)accessType permissions:(NSArray<DBXSHARINGMemberPermission *> * _Nullable)permissions initials:(NSString * _Nullable)initials isInherited:(NSNumber * _Nullable)isInherited;

/// Convenience constructor for the `MembershipInfo` struct (exposes only
/// non-nullable instance variables with no default value).
- (nonnull instancetype)initWithAccessType:(DBXSHARINGAccessLevel * _Nonnull)accessType;

/// Returns a human-readable representation of the `DBXSHARINGMembershipInfo`
/// object.
- (NSString * _Nonnull)description;

@end


/// 
/// The serialization class for the `DBXSHARINGMembershipInfo` struct.
/// 
@interface DBXSHARINGMembershipInfoSerializer : NSObject 

/// Returns a json-compatible dictionary representation of the
/// `DBXSHARINGMembershipInfo` object from an instantiation.
+ (NSDictionary * _Nonnull)serialize:(DBXSHARINGMembershipInfo * _Nonnull)obj;

/// Returns an instantiation of the `DBXSHARINGMembershipInfo` object from a
/// json-compatible dictionary representation.
+ (DBXSHARINGMembershipInfo * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
