///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DbxStoneSerializers.h"

@class DbxFilesLookupError;
@class DbxSharingListSharedLinksError;

/// 
/// The DbxSharingListSharedLinksError union.
/// 
@interface DbxSharingListSharedLinksError : NSObject <DbxSerializable> 

typedef NS_ENUM(NSInteger, SharingListSharedLinksErrorTag) {
    /// (no description)
    SharingListSharedLinksErrorPath,
    /// Indicates that the cursor has been invalidated. Call listSharedLinks to
    /// obtain a new cursor.
    SharingListSharedLinksErrorReset,
    /// (no description)
    SharingListSharedLinksErrorOther,
};

- (nonnull instancetype)initWithPath:(DbxFilesLookupError * _Nonnull)path;

- (nonnull instancetype)initWithReset;

- (nonnull instancetype)initWithOther;

- (BOOL)isPath;

- (BOOL)isReset;

- (BOOL)isOther;

- (NSString * _Nonnull)getTagName;

+ (NSDictionary * _Nonnull)serialize:(id _Nonnull)obj;

+ (id _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

- (NSString * _Nonnull)description;

/// Current state of the DbxSharingListSharedLinksError union type.
@property (nonatomic) SharingListSharedLinksErrorTag tag;
@property (nonatomic) DbxFilesLookupError * _Nonnull path;

@end


@interface DbxSharingListSharedLinksErrorSerializer : NSObject 

+ (NSDictionary * _Nonnull)serialize:(DbxSharingListSharedLinksError * _Nonnull)obj;

+ (DbxSharingListSharedLinksError * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
