///
/// Auto-generated by Stone, do not modify.
///

#import "DbxSharingListSharedLinksResult.h"
#import "DbxSharingSharedLinkMetadata.h"
#import "DbxStoneSerializers.h"
#import "DbxStoneValidators.h"

@implementation DbxSharingListSharedLinksResult 

- (instancetype)initWithLinks:(NSArray<DbxSharingSharedLinkMetadata *> *)links hasMore:(NSNumber *)hasMore cursor:(NSString *)cursor {
    [DbxStoneValidators arrayValidator:nil maxItems:nil itemValidator:nil](links);

    self = [super init];
    if (self != nil) {
        _links = links;
        _hasMore = hasMore;
        _cursor = cursor;
    }
    return self;
}

- (instancetype)initWithLinks:(NSArray<DbxSharingSharedLinkMetadata *> *)links hasMore:(NSNumber *)hasMore {
    return [self initWithLinks:links hasMore:hasMore cursor:nil];
}

+ (NSDictionary *)serialize:(id)obj {
    return [DbxSharingListSharedLinksResultSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DbxSharingListSharedLinksResultSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DbxSharingListSharedLinksResultSerializer serialize:self] description];
}

@end


@implementation DbxSharingListSharedLinksResultSerializer 

+ (NSDictionary *)serialize:(DbxSharingListSharedLinksResult *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    jsonDict[@"links"] = [DbxArraySerializer serialize:valueObj.links withBlock:^id(id elem) { return [DbxSharingSharedLinkMetadataSerializer serialize:elem]; }];
    jsonDict[@"has_more"] = valueObj.hasMore;
    if (valueObj.cursor) {
        jsonDict[@"cursor"] = valueObj.cursor;
    }

    return jsonDict;
}

+ (DbxSharingListSharedLinksResult *)deserialize:(NSDictionary *)valueDict {
    NSArray<DbxSharingSharedLinkMetadata *> *links = [DbxArraySerializer deserialize:valueDict[@"links"] withBlock:^id(id elem) { return [DbxSharingSharedLinkMetadataSerializer deserialize:elem]; }];
    NSNumber *hasMore = valueDict[@"has_more"];
    NSString *cursor = valueDict[@"cursor"] ? valueDict[@"cursor"] : nil;

    return [[DbxSharingListSharedLinksResult alloc] initWithLinks:links hasMore:hasMore cursor:cursor];
}

@end
