///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXSHARINGMountFolderArg;

/// 
/// The MountFolderArg struct.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXSHARINGMountFolderArg : NSObject <DBXSerializable> 

/// The ID of the shared folder to mount.
@property (nonatomic, readonly, copy) NSString * _Nonnull sharedFolderId;

/// 
/// Full constructor for the `DBXSHARINGMountFolderArg` struct (exposes all
/// instance variables).
/// 
/// - parameter sharedFolderId: The ID of the shared folder to mount.
/// 
/// - returns: An initialized `DBXSHARINGMountFolderArg` instance.
/// 
- (nonnull instancetype)initWithSharedFolderId:(NSString * _Nonnull)sharedFolderId;

@end


/// 
/// The serialization class for the MountFolderArg struct.
/// 
@interface DBXSHARINGMountFolderArgSerializer : NSObject 

/// 
/// Serializes `DBXSHARINGMountFolderArg` instances.
/// 
///  - parameter instance: An instance of the `DBXSHARINGMountFolderArg` API
/// object.
/// 
///  - returns: A json-compatible dictionary representation of the
/// `DBXSHARINGMountFolderArg` API object.
/// 
+ (NSDictionary * _Nonnull)serialize:(DBXSHARINGMountFolderArg * _Nonnull)instance;

/// 
/// Deserializes `DBXSHARINGMountFolderArg` instances.
/// 
///  - parameter dict: A json-compatible dictionary representation of the
/// `DBXSHARINGMountFolderArg` API object.
/// 
///  - returns: An instantiation of the `DBXSHARINGMountFolderArg` object.
/// 
+ (DBXSHARINGMountFolderArg * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
