///
/// Auto-generated by Stone, do not modify.
///

#import "DbxAsyncPollResultBase.h"
#import "DbxSharingShareFolderError.h"
#import "DbxSharingShareFolderJobStatus.h"
#import "DbxSharingSharedFolderMetadata.h"
#import "DbxStoneSerializers.h"
#import "DbxStoneValidators.h"

@implementation DbxSharingShareFolderJobStatus 

- (instancetype)initWithInProgress {
    self = [super init];
    if (self != nil) {
        _tag = SharingShareFolderJobStatusInProgress;
    }
    return self;
}

- (instancetype)initWithComplete:(DbxSharingSharedFolderMetadata *)complete {
    self = [super init];
    if (self != nil) {
        _tag = SharingShareFolderJobStatusComplete;
        _complete = complete;
    }
    return self;
}

- (instancetype)initWithFailed:(DbxSharingShareFolderError *)failed {
    self = [super init];
    if (self != nil) {
        _tag = SharingShareFolderJobStatusFailed;
        _failed = failed;
    }
    return self;
}

- (BOOL)isInProgress {
    return _tag == SharingShareFolderJobStatusInProgress;
}

- (BOOL)isComplete {
    return _tag == SharingShareFolderJobStatusComplete;
}

- (BOOL)isFailed {
    return _tag == SharingShareFolderJobStatusFailed;
}

- (NSString *)getTagName {
    switch (_tag) {
        case SharingShareFolderJobStatusInProgress:
           return @"SharingShareFolderJobStatusInProgress";
        case SharingShareFolderJobStatusComplete:
           return @"SharingShareFolderJobStatusComplete";
        case SharingShareFolderJobStatusFailed:
           return @"SharingShareFolderJobStatusFailed";
    }

    @throw([NSException exceptionWithName:@"InvalidTagEnum" reason:@"Supplied tag enum has an invalid value." userInfo:nil]);
}

- (DbxSharingSharedFolderMetadata *)complete {
    if (_tag != SharingShareFolderJobStatusComplete) {
        [NSException raise:@"IllegalStateException" format:@"Invalid tag: required SharingShareFolderJobStatusComplete, but was %@.", [self getTagName]];
    }
    return _complete;
}

- (DbxSharingShareFolderError *)failed {
    if (_tag != SharingShareFolderJobStatusFailed) {
        [NSException raise:@"IllegalStateException" format:@"Invalid tag: required SharingShareFolderJobStatusFailed, but was %@.", [self getTagName]];
    }
    return _failed;
}

+ (NSDictionary *)serialize:(id)obj {
    return [DbxSharingShareFolderJobStatusSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DbxSharingShareFolderJobStatusSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DbxSharingShareFolderJobStatusSerializer serialize:self] description];
}

@end


@implementation DbxSharingShareFolderJobStatusSerializer 

+ (NSDictionary *)serialize:(DbxSharingShareFolderJobStatus *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    if ([valueObj isInProgress]) {
        jsonDict[@".tag"] = @"in_progress";
    }
    else if ([valueObj isComplete]) {
        jsonDict = [[DbxSharingSharedFolderMetadataSerializer serialize:valueObj.complete] mutableCopy];
        jsonDict[@".tag"] = @"complete";
    }
    else if ([valueObj isFailed]) {
        jsonDict = [[DbxSharingShareFolderErrorSerializer serialize:valueObj.failed] mutableCopy];
        jsonDict[@".tag"] = @"failed";
    }
    else {
        @throw([NSException exceptionWithName:@"InvalidTagEnum" reason:@"Supplied tag enum has an invalid value." userInfo:nil]);
    }

    return jsonDict;
}

+ (DbxSharingShareFolderJobStatus *)deserialize:(NSDictionary *)valueDict {
    NSString *tag = valueDict[@".tag"];

    if ([tag isEqualToString:@"in_progress"]) {
        return [[DbxSharingShareFolderJobStatus alloc] initWithInProgress];
    }
    if ([tag isEqualToString:@"complete"]) {
        DbxSharingSharedFolderMetadata *complete = [DbxSharingSharedFolderMetadataSerializer deserialize:valueDict];
        return [[DbxSharingShareFolderJobStatus alloc] initWithComplete:complete];
    }
    if ([tag isEqualToString:@"failed"]) {
        DbxSharingShareFolderError *failed = [DbxSharingShareFolderErrorSerializer deserialize:valueDict[@"failed"]];
        return [[DbxSharingShareFolderJobStatus alloc] initWithFailed:failed];
    }

    @throw([NSException exceptionWithName:@"InvalidTagEnum" reason:@"Supplied tag enum has an invalid value." userInfo:nil]);
}

@end
