use_frameworks!

target "TestObjectiveDropbox_iOS" do
    platform :ios, '11.0'
    pod 'ObjectiveDropboxOfficial', :path => '../'
    target "TestObjectiveDropbox_iOSTests" do
        pod 'ObjectiveDropboxOfficial', :path => '../'
    end
end

target "TestObjectiveDropbox_macOS" do
    platform :osx, '10.10'
    pod 'ObjectiveDropboxOfficial', :path => '../'
    target "TestObjectiveDropbox_macOSTests" do
        pod 'ObjectiveDropboxOfficial', :path => '../'
    end
end
