use_frameworks!

target "TestObjectiveDropbox_iOS" do
    platform :ios, '9.0'
    pod 'ObjectiveDropboxOfficial', :path => '../'
end

target "TestObjectiveDropbox_macOS" do
    platform :osx, '10.10'
    pod 'ObjectiveDropboxOfficial', :path => '../'
end
