///
/// Copyright (c) 2016 Dropbox, Inc. All rights reserved.
///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBSerializableProtocol.h"

@class DBTEAMRevokeDeviceSessionError;

#pragma mark - API Object

/// 
/// The RevokeDeviceSessionError union.
/// 
/// This class implements the DBSerializable protocol (serialize and deserialize
/// instance methods), which is required for all Obj-C SDK API route objects.
/// 
@interface DBTEAMRevokeDeviceSessionError : NSObject <DBSerializable> 

#pragma mark - Instance fields

/// The DBTEAMRevokeDeviceSessionErrorTag enum type represents the possible tag
/// states with which the DBTEAMRevokeDeviceSessionError union can exist.
typedef NS_ENUM(NSInteger, DBTEAMRevokeDeviceSessionErrorTag) {
    /// Device session not found.
    DBTEAMRevokeDeviceSessionErrorDeviceSessionNotFound,

    /// Member not found.
    DBTEAMRevokeDeviceSessionErrorMemberNotFound,

    /// (no description).
    DBTEAMRevokeDeviceSessionErrorOther,

};

/// Represents the union's current tag state.
@property (nonatomic, readonly) DBTEAMRevokeDeviceSessionErrorTag tag;

#pragma mark - Constructors

/// 
/// Initializes union class with tag state of DeviceSessionNotFound.
/// 
/// About the DeviceSessionNotFound tag state: Device session not found.
/// 
/// @return An initialized DBTEAMRevokeDeviceSessionError instance.
/// 
- (nonnull instancetype)initWithDeviceSessionNotFound;

/// 
/// Initializes union class with tag state of MemberNotFound.
/// 
/// About the MemberNotFound tag state: Member not found.
/// 
/// @return An initialized DBTEAMRevokeDeviceSessionError instance.
/// 
- (nonnull instancetype)initWithMemberNotFound;

/// 
/// Initializes union class with tag state of Other.
/// 
/// @return An initialized DBTEAMRevokeDeviceSessionError instance.
/// 
- (nonnull instancetype)initWithOther;

#pragma mark - Tag state methods

/// 
/// Retrieves whether the union's current tag state has value
/// DeviceSessionNotFound.
/// 
/// @return Whether the union's current tag state has value
/// DeviceSessionNotFound.
/// 
- (BOOL)isDeviceSessionNotFound;

/// 
/// Retrieves whether the union's current tag state has value MemberNotFound.
/// 
/// @return Whether the union's current tag state has value MemberNotFound.
/// 
- (BOOL)isMemberNotFound;

/// 
/// Retrieves whether the union's current tag state has value Other.
/// 
/// @return Whether the union's current tag state has value Other.
/// 
- (BOOL)isOther;

/// 
/// Retrieves string value of union's current tag state.
/// 
/// @return A human-readable string representing the union's current tag state.
/// 
- (NSString * _Nonnull)tagName;

@end


#pragma mark - Serializer Object

/// 
/// The serialization class for the DBTEAMRevokeDeviceSessionError union.
/// 
@interface DBTEAMRevokeDeviceSessionErrorSerializer : NSObject 

/// 
/// Serializes DBTEAMRevokeDeviceSessionError instances.
/// 
/// @param instance An instance of the DBTEAMRevokeDeviceSessionError API
/// object.
/// 
/// @return A json-compatible dictionary representation of the
/// DBTEAMRevokeDeviceSessionError API object.
/// 
+ (NSDictionary * _Nonnull)serialize:(DBTEAMRevokeDeviceSessionError * _Nonnull)instance;

/// 
/// Deserializes DBTEAMRevokeDeviceSessionError instances.
/// 
/// @param dict A json-compatible dictionary representation of the
/// DBTEAMRevokeDeviceSessionError API object.
/// 
/// @return An instantiation of the DBTEAMRevokeDeviceSessionError object.
/// 
+ (DBTEAMRevokeDeviceSessionError * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
