///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXTEAMUpdatePropertyTemplateResult;

/// 
/// The UpdatePropertyTemplateResult struct.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXTEAMUpdatePropertyTemplateResult : NSObject <DBXSerializable> 

/// An identifier for property template added by propertiesTemplateAdd.
@property (nonatomic, readonly, copy) NSString * _Nonnull templateId;

/// 
/// Full constructor for the `DBXTEAMUpdatePropertyTemplateResult` struct
/// (exposes all instance variables).
/// 
/// - parameter templateId: An identifier for property template added by
/// :route:`properties/template/add`.
/// 
/// - returns: An initialized `DBXTEAMUpdatePropertyTemplateResult` instance.
/// 
- (nonnull instancetype)initWithTemplateId:(NSString * _Nonnull)templateId;

@end


/// 
/// The serialization class for the UpdatePropertyTemplateResult struct.
/// 
@interface DBXTEAMUpdatePropertyTemplateResultSerializer : NSObject 

/// 
/// Serializes `DBXTEAMUpdatePropertyTemplateResult` instances.
/// 
///  - parameter instance: An instance of the
/// `DBXTEAMUpdatePropertyTemplateResult` API object.
/// 
///  - returns: A json-compatible dictionary representation of the
/// `DBXTEAMUpdatePropertyTemplateResult` API object.
/// 
+ (NSDictionary * _Nonnull)serialize:(DBXTEAMUpdatePropertyTemplateResult * _Nonnull)instance;

/// 
/// Deserializes `DBXTEAMUpdatePropertyTemplateResult` instances.
/// 
///  - parameter dict: A json-compatible dictionary representation of the
/// `DBXTEAMUpdatePropertyTemplateResult` API object.
/// 
///  - returns: An instantiation of the `DBXTEAMUpdatePropertyTemplateResult`
/// object.
/// 
+ (DBXTEAMUpdatePropertyTemplateResult * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
