///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXTEAMListMemberAppsArg;

/// 
/// The ListMemberAppsArg struct.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXTEAMListMemberAppsArg : NSObject <DBXSerializable> 

/// The team member id
@property (nonatomic, readonly, copy) NSString * _Nonnull teamMemberId;

/// 
/// Full constructor for the `DBXTEAMListMemberAppsArg` struct (exposes all
/// instance variables).
/// 
/// - parameter teamMemberId: The team member id
/// 
/// - returns: An initialized `DBXTEAMListMemberAppsArg` instance.
/// 
- (nonnull instancetype)initWithTeamMemberId:(NSString * _Nonnull)teamMemberId;

@end


/// 
/// The serialization class for the ListMemberAppsArg struct.
/// 
@interface DBXTEAMListMemberAppsArgSerializer : NSObject 

/// 
/// Serializes `DBXTEAMListMemberAppsArg` instances.
/// 
///  - parameter instance: An instance of the `DBXTEAMListMemberAppsArg` API
/// object.
/// 
///  - returns: A json-compatible dictionary representation of the
/// `DBXTEAMListMemberAppsArg` API object.
/// 
+ (NSDictionary * _Nonnull)serialize:(DBXTEAMListMemberAppsArg * _Nonnull)instance;

/// 
/// Deserializes `DBXTEAMListMemberAppsArg` instances.
/// 
///  - parameter dict: A json-compatible dictionary representation of the
/// `DBXTEAMListMemberAppsArg` API object.
/// 
///  - returns: An instantiation of the `DBXTEAMListMemberAppsArg` object.
/// 
+ (DBXTEAMListMemberAppsArg * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
