///
/// Auto-generated by Stone, do not modify.
///

#import "DbxStoneSerializers.h"
#import "DbxStoneValidators.h"
#import "DbxTeamRevokeDeviceSessionArg.h"
#import "DbxTeamRevokeDeviceSessionBatchArg.h"

@implementation DbxTeamRevokeDeviceSessionBatchArg 

- (instancetype)initWithRevokeDevices:(NSArray<DbxTeamRevokeDeviceSessionArg *> *)revokeDevices {
    [DbxStoneValidators arrayValidator:nil maxItems:nil itemValidator:nil](revokeDevices);

    self = [super init];
    if (self != nil) {
        _revokeDevices = revokeDevices;
    }
    return self;
}

+ (NSDictionary *)serialize:(id)obj {
    return [DbxTeamRevokeDeviceSessionBatchArgSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DbxTeamRevokeDeviceSessionBatchArgSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DbxTeamRevokeDeviceSessionBatchArgSerializer serialize:self] description];
}

@end


@implementation DbxTeamRevokeDeviceSessionBatchArgSerializer 

+ (NSDictionary *)serialize:(DbxTeamRevokeDeviceSessionBatchArg *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    jsonDict[@"revoke_devices"] = [DbxArraySerializer serialize:valueObj.revokeDevices withBlock:^id(id elem) { return [DbxTeamRevokeDeviceSessionArgSerializer serialize:elem]; }];

    return jsonDict;
}

+ (DbxTeamRevokeDeviceSessionBatchArg *)deserialize:(NSDictionary *)valueDict {
    NSArray<DbxTeamRevokeDeviceSessionArg *> *revokeDevices = [DbxArraySerializer deserialize:valueDict[@"revoke_devices"] withBlock:^id(id elem) { return [DbxTeamRevokeDeviceSessionArgSerializer deserialize:elem]; }];

    return [[DbxTeamRevokeDeviceSessionBatchArg alloc] initWithRevokeDevices:revokeDevices];
}

@end
