///
/// Auto-generated by Stone, do not modify.
///

#import "DBXStoneSerializers.h"
#import "DBXStoneValidators.h"
#import "DBXTEAMDeviceSessionArg.h"

@implementation DBXTEAMDeviceSessionArg 

- (instancetype)initWithSessionId:(NSString *)sessionId teamMemberId:(NSString *)teamMemberId {

    self = [super init];
    if (self) {
        _sessionId = sessionId;
        _teamMemberId = teamMemberId;
    }
    return self;
}

+ (NSDictionary *)serialize:(id)instance {
    return [DBXTEAMDeviceSessionArgSerializer serialize:instance];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DBXTEAMDeviceSessionArgSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DBXTEAMDeviceSessionArgSerializer serialize:self] description];
}

@end


@implementation DBXTEAMDeviceSessionArgSerializer 

+ (NSDictionary *)serialize:(DBXTEAMDeviceSessionArg *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    jsonDict[@"session_id"] = valueObj.sessionId;
    jsonDict[@"team_member_id"] = valueObj.teamMemberId;

    return jsonDict;
}

+ (DBXTEAMDeviceSessionArg *)deserialize:(NSDictionary *)valueDict {
    NSString *sessionId = valueDict[@"session_id"];
    NSString *teamMemberId = valueDict[@"team_member_id"];

    return [[DBXTEAMDeviceSessionArg alloc] initWithSessionId:sessionId teamMemberId:teamMemberId];
}

@end
