///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXTEAMMembersRecoverArg;
@class DBXTEAMUserSelectorArg;

/// 
/// The MembersRecoverArg struct.
/// 
/// Exactly one of team_member_id, email, or external_id must be provided to
/// identify the user account.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXTEAMMembersRecoverArg : NSObject <DBXSerializable> 

/// Identity of user to recover.
@property (nonatomic, readonly) DBXTEAMUserSelectorArg * _Nonnull user;

/// 
/// Full constructor for the `DBXTEAMMembersRecoverArg` struct (exposes all
/// instance variables).
/// 
/// - parameter user: Identity of user to recover.
/// 
/// - returns: An initialized `DBXTEAMMembersRecoverArg` instance.
/// 
- (nonnull instancetype)initWithUser:(DBXTEAMUserSelectorArg * _Nonnull)user;

@end


/// 
/// The serialization class for the MembersRecoverArg struct.
/// 
@interface DBXTEAMMembersRecoverArgSerializer : NSObject 

/// 
/// Serializes `DBXTEAMMembersRecoverArg` instances.
/// 
///  - parameter instance: An instance of the `DBXTEAMMembersRecoverArg` API
/// object.
/// 
///  - returns: A json-compatible dictionary representation of the
/// `DBXTEAMMembersRecoverArg` API object.
/// 
+ (NSDictionary * _Nonnull)serialize:(DBXTEAMMembersRecoverArg * _Nonnull)instance;

/// 
/// Deserializes `DBXTEAMMembersRecoverArg` instances.
/// 
///  - parameter dict: A json-compatible dictionary representation of the
/// `DBXTEAMMembersRecoverArg` API object.
/// 
///  - returns: An instantiation of the `DBXTEAMMembersRecoverArg` object.
/// 
+ (DBXTEAMMembersRecoverArg * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
