///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"
#import "DBXTEAMIncludeMembersArg.h"

@class DBXTEAMCOMMONGroupManagementType;
@class DBXTEAMGroupSelector;
@class DBXTEAMGroupUpdateArgs;

/// 
/// The `DBXTEAMGroupUpdateArgs` struct.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXTEAMGroupUpdateArgs : DBXTEAMIncludeMembersArg <DBXSerializable> 

/// Specify a group.
@property (nonatomic) DBXTEAMGroupSelector * _Nonnull group;

/// Optional argument. Set group name to this if provided.
@property (nonatomic, copy) NSString * _Nullable dNewGroupName;

/// Optional argument. New group external ID. If the argument is None, the
/// group's external_id won't be updated. If the argument is empty string, the
/// group's external id will be cleared.
@property (nonatomic, copy) NSString * _Nullable dNewGroupExternalId;

/// Set new group management type, if provided.
@property (nonatomic) DBXTEAMCOMMONGroupManagementType * _Nullable dNewGroupManagementType;

/// Full constructor for the `GroupUpdateArgs` struct (exposes all instance
/// variables).
- (nonnull instancetype)initWithGroup:(DBXTEAMGroupSelector * _Nonnull)group returnMembers:(NSNumber * _Nullable)returnMembers dNewGroupName:(NSString * _Nullable)dNewGroupName dNewGroupExternalId:(NSString * _Nullable)dNewGroupExternalId dNewGroupManagementType:(DBXTEAMCOMMONGroupManagementType * _Nullable)dNewGroupManagementType;

/// Convenience constructor for the `GroupUpdateArgs` struct (exposes only
/// non-nullable instance variables with no default value).
- (nonnull instancetype)initWithGroup:(DBXTEAMGroupSelector * _Nonnull)group;

/// Returns a human-readable representation of the `DBXTEAMGroupUpdateArgs`
/// object.
- (NSString * _Nonnull)description;

@end


/// 
/// The serialization class for the `DBXTEAMGroupUpdateArgs` struct.
/// 
@interface DBXTEAMGroupUpdateArgsSerializer : NSObject 

/// Returns a json-compatible dictionary representation of the
/// `DBXTEAMGroupUpdateArgs` object from an instantiation.
+ (NSDictionary * _Nonnull)serialize:(DBXTEAMGroupUpdateArgs * _Nonnull)obj;

/// Returns an instantiation of the `DBXTEAMGroupUpdateArgs` object from a
/// json-compatible dictionary representation.
+ (DBXTEAMGroupUpdateArgs * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
