///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXTEAMUpdatePropertyTemplateResult;

/// 
/// The `DBXTEAMUpdatePropertyTemplateResult` struct.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXTEAMUpdatePropertyTemplateResult : NSObject <DBXSerializable> 

/// An identifier for property template added by propertiesTemplateAdd.
@property (nonatomic, copy) NSString * _Nonnull templateId;

/// Full constructor for the `UpdatePropertyTemplateResult` struct (exposes all
/// instance variables).
- (nonnull instancetype)initWithTemplateId:(NSString * _Nonnull)templateId;

/// Returns a human-readable representation of the
/// `DBXTEAMUpdatePropertyTemplateResult` object.
- (NSString * _Nonnull)description;

@end


/// 
/// The serialization class for the `DBXTEAMUpdatePropertyTemplateResult`
/// struct.
/// 
@interface DBXTEAMUpdatePropertyTemplateResultSerializer : NSObject 

/// Returns a json-compatible dictionary representation of the
/// `DBXTEAMUpdatePropertyTemplateResult` object from an instantiation.
+ (NSDictionary * _Nonnull)serialize:(DBXTEAMUpdatePropertyTemplateResult * _Nonnull)obj;

/// Returns an instantiation of the `DBXTEAMUpdatePropertyTemplateResult` object
/// from a json-compatible dictionary representation.
+ (DBXTEAMUpdatePropertyTemplateResult * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
