///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DbxStoneSerializers.h"

@class DbxTeamListMembersDevicesResult;
@class DbxTeamMemberDevices;

/// 
/// The DbxTeamListMembersDevicesResult struct.
/// 
@interface DbxTeamListMembersDevicesResult : NSObject <DbxSerializable> 

/// The devices of each member of the team
@property (nonatomic) NSArray<DbxTeamMemberDevices *> * _Nonnull devices;
/// If true, then there are more devices available. Pass the cursor to
/// devicesListMembersDevices to retrieve the rest.
@property (nonatomic, copy) NSNumber * _Nonnull hasMore;
/// Pass the cursor into devicesListMembersDevices to receive the next sub list
/// of team's devices.
@property (nonatomic, copy) NSString * _Nullable cursor;

- (nonnull instancetype)initWithDevices:(NSArray<DbxTeamMemberDevices *> * _Nonnull)devices hasMore:(NSNumber * _Nonnull)hasMore cursor:(NSString * _Nullable)cursor;

- (nonnull instancetype)initWithDevices:(NSArray<DbxTeamMemberDevices *> * _Nonnull)devices hasMore:(NSNumber * _Nonnull)hasMore;

- (NSString * _Nonnull)description;

@end


@interface DbxTeamListMembersDevicesResultSerializer : NSObject 

+ (NSDictionary * _Nonnull)serialize:(DbxTeamListMembersDevicesResult * _Nonnull)obj;

+ (DbxTeamListMembersDevicesResult * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
