///
/// Auto-generated by Stone, do not modify.
///

#import "DBXStoneSerializers.h"
#import "DBXStoneValidators.h"
#import "DBXTEAMListMembersAppsArg.h"

@implementation DBXTEAMListMembersAppsArg 

- (instancetype)initWithCursor:(NSString *)cursor {

    self = [super init];
    if (self != nil) {
        _cursor = cursor;
    }
    return self;
}

- (instancetype)init {
    return [self initWithCursor:nil];
}

+ (NSDictionary *)serialize:(id)obj {
    return [DBXTEAMListMembersAppsArgSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DBXTEAMListMembersAppsArgSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DBXTEAMListMembersAppsArgSerializer serialize:self] description];
}

@end


@implementation DBXTEAMListMembersAppsArgSerializer 

+ (NSDictionary *)serialize:(DBXTEAMListMembersAppsArg *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    if (valueObj.cursor) {
        jsonDict[@"cursor"] = valueObj.cursor;
    }

    return jsonDict;
}

+ (DBXTEAMListMembersAppsArg *)deserialize:(NSDictionary *)valueDict {
    NSString *cursor = valueDict[@"cursor"] ?: nil;

    return [[DBXTEAMListMembersAppsArg alloc] initWithCursor:cursor];
}

@end
