///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DbxStoneSerializers.h"
#import "DbxTeamGroupSelectorError.h"

@class DbxTeamGroupMembersSelectorError;

/// 
/// The DbxTeamGroupMembersSelectorError union.
/// 
/// Error that can be raised when GroupMembersSelector is used, and the users
/// are required to be members of the specified group.
/// 
@interface DbxTeamGroupMembersSelectorError : NSObject <DbxSerializable> 

typedef NS_ENUM(NSInteger, TeamGroupMembersSelectorErrorTag) {
    /// No matching group found. No groups match the specified group ID.
    TeamGroupMembersSelectorErrorGroupNotFound,
    /// (no description)
    TeamGroupMembersSelectorErrorOther,
    /// At least one of the specified users is not a member of the group.
    TeamGroupMembersSelectorErrorMemberNotInGroup,
};

- (nonnull instancetype)initWithGroupNotFound;

- (nonnull instancetype)initWithOther;

- (nonnull instancetype)initWithMemberNotInGroup;

- (BOOL)isGroupNotFound;

- (BOOL)isOther;

- (BOOL)isMemberNotInGroup;

- (NSString * _Nonnull)getTagName;

- (NSString * _Nonnull)description;

/// Current state of the DbxTeamGroupMembersSelectorError union type.
@property (nonatomic) TeamGroupMembersSelectorErrorTag tag;

@end


@interface DbxTeamGroupMembersSelectorErrorSerializer : NSObject 

+ (NSDictionary * _Nonnull)serialize:(DbxTeamGroupMembersSelectorError * _Nonnull)obj;

+ (DbxTeamGroupMembersSelectorError * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
