///
/// Auto-generated by Stone, do not modify.
///

#import "DBXStoneSerializers.h"
#import "DBXStoneValidators.h"
#import "DBXTEAMRemovedStatus.h"

@implementation DBXTEAMRemovedStatus 

- (instancetype)initWithIsRecoverable:(NSNumber *)isRecoverable {

    self = [super init];
    if (self) {
        _isRecoverable = isRecoverable;
    }
    return self;
}

+ (NSDictionary *)serialize:(id)instance {
    return [DBXTEAMRemovedStatusSerializer serialize:instance];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DBXTEAMRemovedStatusSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DBXTEAMRemovedStatusSerializer serialize:self] description];
}

@end


@implementation DBXTEAMRemovedStatusSerializer 

+ (NSDictionary *)serialize:(DBXTEAMRemovedStatus *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    jsonDict[@"is_recoverable"] = valueObj.isRecoverable;

    return jsonDict;
}

+ (DBXTEAMRemovedStatus *)deserialize:(NSDictionary *)valueDict {
    NSNumber *isRecoverable = valueDict[@"is_recoverable"];

    return [[DBXTEAMRemovedStatus alloc] initWithIsRecoverable:isRecoverable];
}

@end
