///
/// Auto-generated by Stone, do not modify.
///

#import "DbxStoneSerializers.h"
#import "DbxStoneValidators.h"
#import "DbxTeamCommonGroupManagementType.h"
#import "DbxTeamGroupCreateArg.h"

@implementation DbxTeamGroupCreateArg 

- (instancetype)initWithGroupName:(NSString *)groupName groupExternalId:(NSString *)groupExternalId groupManagementType:(DbxTeamCommonGroupManagementType *)groupManagementType {

    self = [super init];
    if (self != nil) {
        _groupName = groupName;
        _groupExternalId = groupExternalId;
        _groupManagementType = groupManagementType;
    }
    return self;
}

- (instancetype)initWithGroupName:(NSString *)groupName {
    return [self initWithGroupName:groupName groupExternalId:nil groupManagementType:nil];
}

+ (NSDictionary *)serialize:(id)obj {
    return [DbxTeamGroupCreateArgSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DbxTeamGroupCreateArgSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DbxTeamGroupCreateArgSerializer serialize:self] description];
}

@end


@implementation DbxTeamGroupCreateArgSerializer 

+ (NSDictionary *)serialize:(DbxTeamGroupCreateArg *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    jsonDict[@"group_name"] = [DbxStringSerializer serialize:valueObj.groupName];
    if (valueObj.groupExternalId != nil) {
        jsonDict[@"group_external_id"] = [DbxStringSerializer serialize:valueObj.groupExternalId];
    }
    if (valueObj.groupManagementType != nil) {
        jsonDict[@"group_management_type"] = [DbxTeamCommonGroupManagementTypeSerializer serialize:valueObj.groupManagementType];
    }

    return jsonDict;
}

+ (DbxTeamGroupCreateArg *)deserialize:(NSDictionary *)valueDict {
    NSString *groupName = [DbxStringSerializer deserialize:valueDict[@"group_name"]];
    NSString *groupExternalId = valueDict[@"group_external_id"] != nil ? [DbxStringSerializer deserialize:valueDict[@"group_external_id"]] : nil;
    DbxTeamCommonGroupManagementType *groupManagementType = valueDict[@"group_management_type"] != nil ? [DbxTeamCommonGroupManagementTypeSerializer deserialize:valueDict[@"group_management_type"]] : nil;

    return [[DbxTeamGroupCreateArg alloc] initWithGroupName:groupName groupExternalId:groupExternalId groupManagementType:groupManagementType];
}

@end
