///
/// Auto-generated by Stone, do not modify.
///

#import "DbxStoneSerializers.h"
#import "DbxStoneValidators.h"
#import "DbxTeamMembersListArg.h"

@implementation DbxTeamMembersListArg 

- (instancetype)initWithLimit:(NSNumber *)limit includeRemoved:(NSNumber *)includeRemoved {
    [DbxStoneValidators numericValidator:[NSNumber numberWithInt:1] maxValue:[NSNumber numberWithInt:1000]](limit ?: [NSNumber numberWithUnsignedInt:1000]);

    self = [super init];
    if (self != nil) {
        _limit = limit ?: [NSNumber numberWithUnsignedInt:1000];
        _includeRemoved = includeRemoved ?: @NO;
    }
    return self;
}

- (instancetype)init {
    return [self initWithLimit:nil includeRemoved:nil];
}

+ (NSDictionary *)serialize:(id)obj {
    return [DbxTeamMembersListArgSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DbxTeamMembersListArgSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DbxTeamMembersListArgSerializer serialize:self] description];
}

@end


@implementation DbxTeamMembersListArgSerializer 

+ (NSDictionary *)serialize:(DbxTeamMembersListArg *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    jsonDict[@"limit"] = valueObj.limit;
    jsonDict[@"include_removed"] = valueObj.includeRemoved;

    return jsonDict;
}

+ (DbxTeamMembersListArg *)deserialize:(NSDictionary *)valueDict {
    NSNumber *limit = valueDict[@"limit"];
    NSNumber *includeRemoved = valueDict[@"include_removed"];

    return [[DbxTeamMembersListArg alloc] initWithLimit:limit includeRemoved:includeRemoved];
}

@end
