///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DbxStoneSerializers.h"

@class DbxTeamDateRangeError;

/// 
/// The DbxTeamDateRangeError union.
/// 
/// Errors that can originate from problems in input arguments to reports.
/// 
@interface DbxTeamDateRangeError : NSObject <DbxSerializable> 

typedef NS_ENUM(NSInteger, TeamDateRangeErrorTag) {
    /// (no description)
    TeamDateRangeErrorOther,
};

- (nonnull instancetype)initWithOther;

- (BOOL)isOther;

- (NSString * _Nonnull)getTagName;

- (NSString * _Nonnull)description;

/// Current state of the DbxTeamDateRangeError union type.
@property (nonatomic) TeamDateRangeErrorTag tag;

@end


@interface DbxTeamDateRangeErrorSerializer : NSObject 

+ (NSDictionary * _Nonnull)serialize:(DbxTeamDateRangeError * _Nonnull)obj;

+ (DbxTeamDateRangeError * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
