///
/// Auto-generated by Stone, do not modify.
///

#import "DbxAsyncLaunchResultBase.h"
#import "DbxStoneSerializers.h"
#import "DbxStoneValidators.h"
#import "DbxTeamMemberAddResult.h"
#import "DbxTeamMembersAddLaunch.h"

@implementation DbxTeamMembersAddLaunch 

- (instancetype)initWithAsyncJobId:(NSString *)asyncJobId {
    self = [super init];
    if (self != nil) {
        _tag = (TeamMembersAddLaunchTag)TeamMembersAddLaunchAsyncJobId;
        _asyncJobId = asyncJobId;
    }
    return self;
}

- (instancetype)initWithComplete:(NSArray<DbxTeamMemberAddResult *> *)complete {
    self = [super init];
    if (self != nil) {
        _tag = (TeamMembersAddLaunchTag)TeamMembersAddLaunchComplete;
        _complete = complete;
    }
    return self;
}

- (BOOL)isAsyncJobId {
    return _tag == (TeamMembersAddLaunchTag)TeamMembersAddLaunchAsyncJobId;
}

- (BOOL)isComplete {
    return _tag == (TeamMembersAddLaunchTag)TeamMembersAddLaunchComplete;
}

- (NSString *)getTagName {
    if (_tag == (TeamMembersAddLaunchTag)TeamMembersAddLaunchAsyncJobId) {
        return @"(TeamMembersAddLaunchTag)TeamMembersAddLaunchAsyncJobId";
    }
    if (_tag == (TeamMembersAddLaunchTag)TeamMembersAddLaunchComplete) {
        return @"(TeamMembersAddLaunchTag)TeamMembersAddLaunchComplete";
    }

    @throw([NSException exceptionWithName:@"InvalidTagEnum" reason:@"Supplied tag enum has an invalid value." userInfo:nil]);
}

- (NSString *)asyncJobId {
    if (_tag != (TeamMembersAddLaunchTag)TeamMembersAddLaunchAsyncJobId) {
        [NSException raise:@"IllegalStateException" format:@"Invalid tag: required (TeamMembersAddLaunchTag)TeamMembersAddLaunchAsyncJobId, but was %@.", [self getTagName]];
    }
    return _asyncJobId;
}

- (NSArray<DbxTeamMemberAddResult *> *)complete {
    if (_tag != (TeamMembersAddLaunchTag)TeamMembersAddLaunchComplete) {
        [NSException raise:@"IllegalStateException" format:@"Invalid tag: required (TeamMembersAddLaunchTag)TeamMembersAddLaunchComplete, but was %@.", [self getTagName]];
    }
    return _complete;
}

+ (NSDictionary *)serialize:(id)obj {
    return [DbxTeamMembersAddLaunchSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DbxTeamMembersAddLaunchSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DbxTeamMembersAddLaunchSerializer serialize:self] description];
}

@end


@implementation DbxTeamMembersAddLaunchSerializer 

+ (NSDictionary *)serialize:(DbxTeamMembersAddLaunch *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    if ([valueObj isAsyncJobId]) {
        jsonDict[@"async_job_id"] = [DbxStringSerializer serialize:valueObj.asyncJobId];
        jsonDict[@".tag"] = @"async_job_id";
    }
    else if ([valueObj isComplete]) {
        jsonDict[@"complete"] = [DbxArraySerializer serialize:valueObj.complete withBlock:^id(id obj) { return [DbxTeamMemberAddResultSerializer serialize:obj]; }];
        jsonDict[@".tag"] = @"complete";
    }
    else {
        @throw([NSException exceptionWithName:@"InvalidTagEnum" reason:@"Supplied tag enum has an invalid value." userInfo:nil]);
    }

    return jsonDict;
}

+ (DbxTeamMembersAddLaunch *)deserialize:(NSDictionary *)valueDict {
    NSString *tag = valueDict[@".tag"];

    if ([tag isEqualToString:@"async_job_id"]) {
        NSString *asyncJobId = [DbxStringSerializer deserialize:valueDict[@"async_job_id"]];
        return [[DbxTeamMembersAddLaunch alloc] initWithAsyncJobId:asyncJobId];
    }
    if ([tag isEqualToString:@"complete"]) {
        NSArray<DbxTeamMemberAddResult *> *complete = [DbxArraySerializer deserialize:valueDict[@"complete"] withBlock:^id(id obj) { return [DbxTeamMemberAddResultSerializer deserialize:obj]; }];
        return [[DbxTeamMembersAddLaunch alloc] initWithComplete:complete];
    }

    @throw([NSException exceptionWithName:@"InvalidTagEnum" reason:@"Supplied tag enum has an invalid value." userInfo:nil]);
}

@end
