///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXTEAMApiApp;
@class DBXTEAMListMemberAppsResult;

/// 
/// The `DBXTEAMListMemberAppsResult` struct.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXTEAMListMemberAppsResult : NSObject <DBXSerializable> 

/// List of third party applications linked by this team member
@property (nonatomic) NSArray<DBXTEAMApiApp *> * _Nonnull linkedApiApps;

/// Full constructor for the `ListMemberAppsResult` struct (exposes all instance
/// variables).
- (nonnull instancetype)initWithLinkedApiApps:(NSArray<DBXTEAMApiApp *> * _Nonnull)linkedApiApps;

/// Returns a human-readable representation of the `DBXTEAMListMemberAppsResult`
/// object.
- (NSString * _Nonnull)description;

@end


/// 
/// The serialization class for the `DBXTEAMListMemberAppsResult` struct.
/// 
@interface DBXTEAMListMemberAppsResultSerializer : NSObject 

/// Returns a json-compatible dictionary representation of the
/// `DBXTEAMListMemberAppsResult` object from an instantiation.
+ (NSDictionary * _Nonnull)serialize:(DBXTEAMListMemberAppsResult * _Nonnull)obj;

/// Returns an instantiation of the `DBXTEAMListMemberAppsResult` object from a
/// json-compatible dictionary representation.
+ (DBXTEAMListMemberAppsResult * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
