///
/// Auto-generated by Stone, do not modify.
///

#import "DBXStoneSerializers.h"
#import "DBXStoneValidators.h"
#import "DBXTEAMUserSelectorError.h"

@implementation DBXTEAMUserSelectorError 

- (instancetype)initWithUserNotFound {
    self = [super init];
    if (self != nil) {
        _tag = DBXTEAMUserSelectorErrorUserNotFound;
    }
    return self;
}

- (BOOL)isUserNotFound {
    return _tag == DBXTEAMUserSelectorErrorUserNotFound;
}

- (NSString *)getTagName {
    switch (_tag) {
        case DBXTEAMUserSelectorErrorUserNotFound:
           return @"DBXTEAMUserSelectorErrorUserNotFound";
    }

    @throw([NSException exceptionWithName:@"InvalidTag" reason:@"Tag has an invalid value." userInfo:nil]);
}

+ (NSDictionary *)serialize:(id)obj {
    return [DBXTEAMUserSelectorErrorSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DBXTEAMUserSelectorErrorSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DBXTEAMUserSelectorErrorSerializer serialize:self] description];
}

@end


@implementation DBXTEAMUserSelectorErrorSerializer 

+ (NSDictionary *)serialize:(DBXTEAMUserSelectorError *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    if ([valueObj isUserNotFound]) {
        jsonDict[@".tag"] = @"user_not_found";
    }
    else {
        @throw([NSException exceptionWithName:@"InvalidTag" reason:@"Tag has an invalid value." userInfo:nil]);
    }

    return jsonDict;
}

+ (DBXTEAMUserSelectorError *)deserialize:(NSDictionary *)valueDict {
    NSString *tag = valueDict[@".tag"];

    if ([tag isEqualToString:@"user_not_found"]) {
        return [[DBXTEAMUserSelectorError alloc] initWithUserNotFound];
    }

    @throw([NSException exceptionWithName:@"InvalidTag" reason:@"Tag has an invalid value." userInfo:nil]);
}

@end
