///
/// Auto-generated by Stone, do not modify.
///

#import "DBXStoneSerializers.h"
#import "DBXStoneValidators.h"
#import "DBXTEAMRevokeDeviceSessionError.h"
#import "DBXTEAMRevokeDeviceSessionStatus.h"

@implementation DBXTEAMRevokeDeviceSessionStatus 

- (instancetype)initWithSuccess:(NSNumber *)success errorType:(DBXTEAMRevokeDeviceSessionError *)errorType {

    self = [super init];
    if (self != nil) {
        _success = success;
        _errorType = errorType;
    }
    return self;
}

- (instancetype)initWithSuccess:(NSNumber *)success {
    return [self initWithSuccess:success errorType:nil];
}

+ (NSDictionary *)serialize:(id)obj {
    return [DBXTEAMRevokeDeviceSessionStatusSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DBXTEAMRevokeDeviceSessionStatusSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DBXTEAMRevokeDeviceSessionStatusSerializer serialize:self] description];
}

@end


@implementation DBXTEAMRevokeDeviceSessionStatusSerializer 

+ (NSDictionary *)serialize:(DBXTEAMRevokeDeviceSessionStatus *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    jsonDict[@"success"] = valueObj.success;
    if (valueObj.errorType) {
        jsonDict[@"error_type"] = [DBXTEAMRevokeDeviceSessionErrorSerializer serialize:valueObj.errorType];
    }

    return jsonDict;
}

+ (DBXTEAMRevokeDeviceSessionStatus *)deserialize:(NSDictionary *)valueDict {
    NSNumber *success = valueDict[@"success"];
    DBXTEAMRevokeDeviceSessionError *errorType = valueDict[@"error_type"] ? [DBXTEAMRevokeDeviceSessionErrorSerializer deserialize:valueDict[@"error_type"]] : nil;

    return [[DBXTEAMRevokeDeviceSessionStatus alloc] initWithSuccess:success errorType:errorType];
}

@end
