///
/// Auto-generated by Stone, do not modify.
///

#import "DBXStoneSerializers.h"
#import "DBXStoneValidators.h"
#import "DBXTEAMRevokeLinkedAppBatchError.h"

@implementation DBXTEAMRevokeLinkedAppBatchError 

- (instancetype)initWithOther {
    self = [super init];
    if (self) {
        _tag = DBXTEAMRevokeLinkedAppBatchErrorOther;
    }
    return self;
}

- (BOOL)isOther {
    return _tag == DBXTEAMRevokeLinkedAppBatchErrorOther;
}

- (NSString *)getTagName {
    switch (_tag) {
        case DBXTEAMRevokeLinkedAppBatchErrorOther:
           return @"DBXTEAMRevokeLinkedAppBatchErrorOther";
    }

    @throw([NSException exceptionWithName:@"InvalidTag" reason:@"Tag has an invalid value." userInfo:nil]);
}

+ (NSDictionary *)serialize:(id)instance {
    return [DBXTEAMRevokeLinkedAppBatchErrorSerializer serialize:instance];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DBXTEAMRevokeLinkedAppBatchErrorSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DBXTEAMRevokeLinkedAppBatchErrorSerializer serialize:self] description];
}

@end


@implementation DBXTEAMRevokeLinkedAppBatchErrorSerializer 

+ (NSDictionary *)serialize:(DBXTEAMRevokeLinkedAppBatchError *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    if ([valueObj isOther]) {
        jsonDict[@".tag"] = @"other";
    }
    else {
        @throw([NSException exceptionWithName:@"InvalidTag" reason:@"Tag has an invalid value." userInfo:nil]);
    }

    return jsonDict;
}

+ (DBXTEAMRevokeLinkedAppBatchError *)deserialize:(NSDictionary *)valueDict {
    NSString *tag = valueDict[@".tag"];

    if ([tag isEqualToString:@"other"]) {
        return [[DBXTEAMRevokeLinkedAppBatchError alloc] initWithOther];
    }

    @throw([NSException exceptionWithName:@"InvalidTag" reason:@"Tag has an invalid value." userInfo:nil]);
}

@end
