///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DbxStoneSerializers.h"

@class DbxTeamActiveWebSession;
@class DbxTeamDesktopClientSession;
@class DbxTeamMemberDevices;
@class DbxTeamMobileClientSession;

/// 
/// The DbxTeamMemberDevices struct.
/// 
/// Information on devices of a team's member.
/// 
@interface DbxTeamMemberDevices : NSObject <DbxSerializable> 

/// The member unique Id
@property (nonatomic, copy) NSString * _Nonnull teamMemberId;
/// List of web sessions made by this team member
@property (nonatomic) NSArray<DbxTeamActiveWebSession *> * _Nullable webSessions;
/// List of desktop clients by this team member
@property (nonatomic) NSArray<DbxTeamDesktopClientSession *> * _Nullable desktopClients;
/// List of mobile clients by this team member
@property (nonatomic) NSArray<DbxTeamMobileClientSession *> * _Nullable mobileClients;

- (nonnull instancetype)initWithTeamMemberId:(NSString * _Nonnull)teamMemberId webSessions:(NSArray<DbxTeamActiveWebSession *> * _Nullable)webSessions desktopClients:(NSArray<DbxTeamDesktopClientSession *> * _Nullable)desktopClients mobileClients:(NSArray<DbxTeamMobileClientSession *> * _Nullable)mobileClients;

- (nonnull instancetype)initWithTeamMemberId:(NSString * _Nonnull)teamMemberId;

- (NSString * _Nonnull)description;

@end


@interface DbxTeamMemberDevicesSerializer : NSObject 

+ (NSDictionary * _Nonnull)serialize:(DbxTeamMemberDevices * _Nonnull)obj;

+ (DbxTeamMemberDevices * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
