///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXTEAMDeviceSessionArg;
@class DBXTEAMRevokeDesktopClientArg;
@class DBXTEAMRevokeDeviceSessionArg;

/// 
/// The `DBXTEAMRevokeDeviceSessionArg` union.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
@interface DBXTEAMRevokeDeviceSessionArg : NSObject <DBXSerializable> 

/// The `DBXTEAMRevokeDeviceSessionArgTag` enum type represents the possible tag
/// states that the `DBXTEAMRevokeDeviceSessionArg` union can exist in.
typedef NS_ENUM(NSInteger, DBXTEAMRevokeDeviceSessionArgTag) {
    /// End an active session
    DBXTEAMRevokeDeviceSessionArgWebSession,

    /// Unlink a linked desktop device
    DBXTEAMRevokeDeviceSessionArgDesktopClient,

    /// Unlink a linked mobile device
    DBXTEAMRevokeDeviceSessionArgMobileClient,

};

/// Represents the union's current tag state.
@property (nonatomic, readonly) DBXTEAMRevokeDeviceSessionArgTag tag;

/// End an active session
@property (nonatomic, readonly) DBXTEAMDeviceSessionArg * _Nonnull webSession;

/// Unlink a linked desktop device
@property (nonatomic, readonly) DBXTEAMRevokeDesktopClientArg * _Nonnull desktopClient;

/// Unlink a linked mobile device
@property (nonatomic, readonly) DBXTEAMDeviceSessionArg * _Nonnull mobileClient;

/// Initializes union class with tag state of `WebSession`.
- (nonnull instancetype)initWithWebSession:(DBXTEAMDeviceSessionArg * _Nonnull)webSession;

/// Initializes union class with tag state of `DesktopClient`.
- (nonnull instancetype)initWithDesktopClient:(DBXTEAMRevokeDesktopClientArg * _Nonnull)desktopClient;

/// Initializes union class with tag state of `MobileClient`.
- (nonnull instancetype)initWithMobileClient:(DBXTEAMDeviceSessionArg * _Nonnull)mobileClient;

/// Returns whether the union's current tag state has value `WebSession`.
- (BOOL)isWebSession;

/// Returns whether the union's current tag state has value `DesktopClient`.
- (BOOL)isDesktopClient;

/// Returns whether the union's current tag state has value `MobileClient`.
- (BOOL)isMobileClient;

/// Returns a human-readable string representing the union's current tag state.
- (NSString * _Nonnull)getTagName;

@end


/// 
/// The serialization class for the `DBXTEAMRevokeDeviceSessionArg` union.
/// 
@interface DBXTEAMRevokeDeviceSessionArgSerializer : NSObject 

/// Returns a json-compatible dictionary representation of the
/// `DBXTEAMRevokeDeviceSessionArg` object from an instantiation.
+ (NSDictionary * _Nonnull)serialize:(DBXTEAMRevokeDeviceSessionArg * _Nonnull)obj;

/// Returns an instantiation of the `DBXTEAMRevokeDeviceSessionArg` object from
/// a json-compatible dictionary representation.
+ (DBXTEAMRevokeDeviceSessionArg * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
