///
/// Auto-generated by Stone, do not modify.
///

#import "DbxStoneSerializers.h"
#import "DbxStoneValidators.h"
#import "DbxTeamRemovedStatus.h"

@implementation DbxTeamRemovedStatus 

- (instancetype)initWithIsRecoverable:(NSNumber *)isRecoverable {

    self = [super init];
    if (self != nil) {
        _isRecoverable = isRecoverable;
    }
    return self;
}

+ (NSDictionary *)serialize:(id)obj {
    return [DbxTeamRemovedStatusSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DbxTeamRemovedStatusSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DbxTeamRemovedStatusSerializer serialize:self] description];
}

@end


@implementation DbxTeamRemovedStatusSerializer 

+ (NSDictionary *)serialize:(DbxTeamRemovedStatus *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    jsonDict[@"is_recoverable"] = valueObj.isRecoverable;

    return jsonDict;
}

+ (DbxTeamRemovedStatus *)deserialize:(NSDictionary *)valueDict {
    NSNumber *isRecoverable = valueDict[@"is_recoverable"];

    return [[DbxTeamRemovedStatus alloc] initWithIsRecoverable:isRecoverable];
}

@end
