///
/// Auto-generated by Stone, do not modify.
///

#import "DBXStoneSerializers.h"
#import "DBXStoneValidators.h"
#import "DBXTEAMRevokeLinkedApiAppArg.h"

@implementation DBXTEAMRevokeLinkedApiAppArg 

- (instancetype)initWithAppId:(NSString *)appId teamMemberId:(NSString *)teamMemberId keepAppFolder:(NSNumber *)keepAppFolder {

    self = [super init];
    if (self != nil) {
        _appId = appId;
        _teamMemberId = teamMemberId;
        _keepAppFolder = keepAppFolder ?: @YES;
    }
    return self;
}

- (instancetype)initWithAppId:(NSString *)appId teamMemberId:(NSString *)teamMemberId {
    return [self initWithAppId:appId teamMemberId:teamMemberId keepAppFolder:nil];
}

+ (NSDictionary *)serialize:(id)obj {
    return [DBXTEAMRevokeLinkedApiAppArgSerializer serialize:obj];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DBXTEAMRevokeLinkedApiAppArgSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DBXTEAMRevokeLinkedApiAppArgSerializer serialize:self] description];
}

@end


@implementation DBXTEAMRevokeLinkedApiAppArgSerializer 

+ (NSDictionary *)serialize:(DBXTEAMRevokeLinkedApiAppArg *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    jsonDict[@"app_id"] = valueObj.appId;
    jsonDict[@"team_member_id"] = valueObj.teamMemberId;
    jsonDict[@"keep_app_folder"] = valueObj.keepAppFolder;

    return jsonDict;
}

+ (DBXTEAMRevokeLinkedApiAppArg *)deserialize:(NSDictionary *)valueDict {
    NSString *appId = valueDict[@"app_id"];
    NSString *teamMemberId = valueDict[@"team_member_id"];
    NSNumber *keepAppFolder = valueDict[@"keep_app_folder"];

    return [[DBXTEAMRevokeLinkedApiAppArg alloc] initWithAppId:appId teamMemberId:teamMemberId keepAppFolder:keepAppFolder];
}

@end
