///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DBXSerializableProtocol.h"

@class DBXTEAMRemovedStatus;
@class DBXTEAMTeamMemberStatus;

/// 
/// The `DBXTEAMTeamMemberStatus` union.
/// 
/// This class implements the `DBXSerializable` protocol (`serialize` and
/// `deserialize` instance methods), which is required for all Obj-C SDK API
/// route objects.
/// 
/// The user's status as a member of a specific team.
/// 
@interface DBXTEAMTeamMemberStatus : NSObject <DBXSerializable> 

/// The `DBXTEAMTeamMemberStatusTag` enum type represents the possible tag
/// states that the `DBXTEAMTeamMemberStatus` union can exist in.
typedef NS_ENUM(NSInteger, DBXTEAMTeamMemberStatusTag) {
    /// User has successfully joined the team.
    DBXTEAMTeamMemberStatusActive,

    /// User has been invited to a team, but has not joined the team yet.
    DBXTEAMTeamMemberStatusInvited,

    /// User is no longer a member of the team, but the account can be
    /// un-suspended, re-establishing the user as a team member.
    DBXTEAMTeamMemberStatusSuspended,

    /// User is no longer a member of the team. Removed users are only listed
    /// when include_removed is true in members/list.
    DBXTEAMTeamMemberStatusRemoved,

};

/// Represents the union's current tag state.
@property (nonatomic, readonly) DBXTEAMTeamMemberStatusTag tag;

/// User is no longer a member of the team. Removed users are only listed when
/// include_removed is true in members/list.
@property (nonatomic, readonly) DBXTEAMRemovedStatus * _Nonnull removed;

/// Initializes union class with tag state of `Active`.
- (nonnull instancetype)initWithActive;

/// Initializes union class with tag state of `Invited`.
- (nonnull instancetype)initWithInvited;

/// Initializes union class with tag state of `Suspended`.
- (nonnull instancetype)initWithSuspended;

/// Initializes union class with tag state of `Removed`.
- (nonnull instancetype)initWithRemoved:(DBXTEAMRemovedStatus * _Nonnull)removed;

/// Returns whether the union's current tag state has value `Active`.
- (BOOL)isActive;

/// Returns whether the union's current tag state has value `Invited`.
- (BOOL)isInvited;

/// Returns whether the union's current tag state has value `Suspended`.
- (BOOL)isSuspended;

/// Returns whether the union's current tag state has value `Removed`.
- (BOOL)isRemoved;

/// Returns a human-readable string representing the union's current tag state.
- (NSString * _Nonnull)getTagName;

@end


/// 
/// The serialization class for the `DBXTEAMTeamMemberStatus` union.
/// 
@interface DBXTEAMTeamMemberStatusSerializer : NSObject 

/// Returns a json-compatible dictionary representation of the
/// `DBXTEAMTeamMemberStatus` object from an instantiation.
+ (NSDictionary * _Nonnull)serialize:(DBXTEAMTeamMemberStatus * _Nonnull)obj;

/// Returns an instantiation of the `DBXTEAMTeamMemberStatus` object from a
/// json-compatible dictionary representation.
+ (DBXTEAMTeamMemberStatus * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
