///
/// Auto-generated by Stone, do not modify.
///

#import "DBXStoneSerializers.h"
#import "DBXStoneValidators.h"
#import "DBXTEAMListMembersAppsResult.h"
#import "DBXTEAMMemberLinkedApps.h"

@implementation DBXTEAMListMembersAppsResult 

- (instancetype)initWithApps:(NSArray<DBXTEAMMemberLinkedApps *> *)apps hasMore:(NSNumber *)hasMore cursor:(NSString *)cursor {
    [DBXStoneValidators arrayValidator:nil maxItems:nil itemValidator:nil](apps);

    self = [super init];
    if (self) {
        _apps = apps;
        _hasMore = hasMore;
        _cursor = cursor;
    }
    return self;
}

- (instancetype)initWithApps:(NSArray<DBXTEAMMemberLinkedApps *> *)apps hasMore:(NSNumber *)hasMore {
    return [self initWithApps:apps hasMore:hasMore cursor:nil];
}

+ (NSDictionary *)serialize:(id)instance {
    return [DBXTEAMListMembersAppsResultSerializer serialize:instance];
}

+ (id)deserialize:(NSDictionary *)dict {
    return [DBXTEAMListMembersAppsResultSerializer deserialize:dict];
}

- (NSString *)description {
    return [[DBXTEAMListMembersAppsResultSerializer serialize:self] description];
}

@end


@implementation DBXTEAMListMembersAppsResultSerializer 

+ (NSDictionary *)serialize:(DBXTEAMListMembersAppsResult *)valueObj {
    NSMutableDictionary *jsonDict = [[NSMutableDictionary alloc] init];

    jsonDict[@"apps"] = [DBXArraySerializer serialize:valueObj.apps withBlock:^id(id elem) { return [DBXTEAMMemberLinkedAppsSerializer serialize:elem]; }];
    jsonDict[@"has_more"] = valueObj.hasMore;
    if (valueObj.cursor) {
        jsonDict[@"cursor"] = valueObj.cursor;
    }

    return jsonDict;
}

+ (DBXTEAMListMembersAppsResult *)deserialize:(NSDictionary *)valueDict {
    NSArray<DBXTEAMMemberLinkedApps *> *apps = [DBXArraySerializer deserialize:valueDict[@"apps"] withBlock:^id(id elem) { return [DBXTEAMMemberLinkedAppsSerializer deserialize:elem]; }];
    NSNumber *hasMore = valueDict[@"has_more"];
    NSString *cursor = valueDict[@"cursor"] ?: nil;

    return [[DBXTEAMListMembersAppsResult alloc] initWithApps:apps hasMore:hasMore cursor:cursor];
}

@end
