///
/// Auto-generated by Stone, do not modify.
///

#import <Foundation/Foundation.h>
#import "DbxStoneSerializers.h"

@class DbxTeamPoliciesSharedFolderJoinPolicy;

/// 
/// The DbxTeamPoliciesSharedFolderJoinPolicy union.
/// 
/// Policy governing which shared folders a team member can join.
/// 
@interface DbxTeamPoliciesSharedFolderJoinPolicy : NSObject <DbxSerializable> 

typedef NS_ENUM(NSInteger, TeamPoliciesSharedFolderJoinPolicyTag) {
    /// Team members can only join folders shared by teammates.
    TeamPoliciesSharedFolderJoinPolicyFromTeamOnly,
    /// Team members can join any shared folder, including those shared by users
    /// outside the team.
    TeamPoliciesSharedFolderJoinPolicyFromAnyone,
    /// (no description)
    TeamPoliciesSharedFolderJoinPolicyOther,
};

- (nonnull instancetype)initWithFromTeamOnly;

- (nonnull instancetype)initWithFromAnyone;

- (nonnull instancetype)initWithOther;

- (BOOL)isFromTeamOnly;

- (BOOL)isFromAnyone;

- (BOOL)isOther;

- (NSString * _Nonnull)getTagName;

- (NSString * _Nonnull)description;

/// Current state of the DbxTeamPoliciesSharedFolderJoinPolicy union type.
@property (nonatomic) TeamPoliciesSharedFolderJoinPolicyTag tag;

@end


@interface DbxTeamPoliciesSharedFolderJoinPolicySerializer : NSObject 

+ (NSDictionary * _Nonnull)serialize:(DbxTeamPoliciesSharedFolderJoinPolicy * _Nonnull)obj;

+ (DbxTeamPoliciesSharedFolderJoinPolicy * _Nonnull)deserialize:(NSDictionary * _Nonnull)dict;

@end
